// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/product/product.proto

package go_micro_bookstore_srv_product

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Book struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	DisplayName          string   `protobuf:"bytes,3,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	Description          string   `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	Cover                string   `protobuf:"bytes,5,opt,name=cover,proto3" json:"cover,omitempty"`
	AuthorId             string   `protobuf:"bytes,6,opt,name=author_id,json=authorId,proto3" json:"author_id,omitempty"`
	Price                float64  `protobuf:"fixed64,7,opt,name=price,proto3" json:"price,omitempty"`
	ReleasedAt           int64    `protobuf:"varint,8,opt,name=released_at,json=releasedAt,proto3" json:"released_at,omitempty"`
	CreatedAt            int64    `protobuf:"varint,9,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt            int64    `protobuf:"varint,10,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Book) Reset()         { *m = Book{} }
func (m *Book) String() string { return proto.CompactTextString(m) }
func (*Book) ProtoMessage()    {}
func (*Book) Descriptor() ([]byte, []int) {
	return fileDescriptor_14fbc13de7c38f78, []int{0}
}

func (m *Book) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Book.Unmarshal(m, b)
}
func (m *Book) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Book.Marshal(b, m, deterministic)
}
func (m *Book) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Book.Merge(m, src)
}
func (m *Book) XXX_Size() int {
	return xxx_messageInfo_Book.Size(m)
}
func (m *Book) XXX_DiscardUnknown() {
	xxx_messageInfo_Book.DiscardUnknown(m)
}

var xxx_messageInfo_Book proto.InternalMessageInfo

func (m *Book) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Book) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Book) GetDisplayName() string {
	if m != nil {
		return m.DisplayName
	}
	return ""
}

func (m *Book) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *Book) GetCover() string {
	if m != nil {
		return m.Cover
	}
	return ""
}

func (m *Book) GetAuthorId() string {
	if m != nil {
		return m.AuthorId
	}
	return ""
}

func (m *Book) GetPrice() float64 {
	if m != nil {
		return m.Price
	}
	return 0
}

func (m *Book) GetReleasedAt() int64 {
	if m != nil {
		return m.ReleasedAt
	}
	return 0
}

func (m *Book) GetCreatedAt() int64 {
	if m != nil {
		return m.CreatedAt
	}
	return 0
}

func (m *Book) GetUpdatedAt() int64 {
	if m != nil {
		return m.UpdatedAt
	}
	return 0
}

type CreateBookRequest struct {
	Book                 *Book    `protobuf:"bytes,1,opt,name=book,proto3" json:"book,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateBookRequest) Reset()         { *m = CreateBookRequest{} }
func (m *CreateBookRequest) String() string { return proto.CompactTextString(m) }
func (*CreateBookRequest) ProtoMessage()    {}
func (*CreateBookRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_14fbc13de7c38f78, []int{1}
}

func (m *CreateBookRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateBookRequest.Unmarshal(m, b)
}
func (m *CreateBookRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateBookRequest.Marshal(b, m, deterministic)
}
func (m *CreateBookRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateBookRequest.Merge(m, src)
}
func (m *CreateBookRequest) XXX_Size() int {
	return xxx_messageInfo_CreateBookRequest.Size(m)
}
func (m *CreateBookRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateBookRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateBookRequest proto.InternalMessageInfo

func (m *CreateBookRequest) GetBook() *Book {
	if m != nil {
		return m.Book
	}
	return nil
}

type CreateBookResponse struct {
	Code                 int32    `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Detail               string   `protobuf:"bytes,2,opt,name=detail,proto3" json:"detail,omitempty"`
	Book                 *Book    `protobuf:"bytes,3,opt,name=book,proto3" json:"book,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateBookResponse) Reset()         { *m = CreateBookResponse{} }
func (m *CreateBookResponse) String() string { return proto.CompactTextString(m) }
func (*CreateBookResponse) ProtoMessage()    {}
func (*CreateBookResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_14fbc13de7c38f78, []int{2}
}

func (m *CreateBookResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateBookResponse.Unmarshal(m, b)
}
func (m *CreateBookResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateBookResponse.Marshal(b, m, deterministic)
}
func (m *CreateBookResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateBookResponse.Merge(m, src)
}
func (m *CreateBookResponse) XXX_Size() int {
	return xxx_messageInfo_CreateBookResponse.Size(m)
}
func (m *CreateBookResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateBookResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateBookResponse proto.InternalMessageInfo

func (m *CreateBookResponse) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *CreateBookResponse) GetDetail() string {
	if m != nil {
		return m.Detail
	}
	return ""
}

func (m *CreateBookResponse) GetBook() *Book {
	if m != nil {
		return m.Book
	}
	return nil
}

type GetBookRequest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetBookRequest) Reset()         { *m = GetBookRequest{} }
func (m *GetBookRequest) String() string { return proto.CompactTextString(m) }
func (*GetBookRequest) ProtoMessage()    {}
func (*GetBookRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_14fbc13de7c38f78, []int{3}
}

func (m *GetBookRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetBookRequest.Unmarshal(m, b)
}
func (m *GetBookRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetBookRequest.Marshal(b, m, deterministic)
}
func (m *GetBookRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetBookRequest.Merge(m, src)
}
func (m *GetBookRequest) XXX_Size() int {
	return xxx_messageInfo_GetBookRequest.Size(m)
}
func (m *GetBookRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetBookRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetBookRequest proto.InternalMessageInfo

func (m *GetBookRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type GetBookResponse struct {
	Code                 int32    `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Detail               string   `protobuf:"bytes,2,opt,name=detail,proto3" json:"detail,omitempty"`
	Book                 *Book    `protobuf:"bytes,3,opt,name=book,proto3" json:"book,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetBookResponse) Reset()         { *m = GetBookResponse{} }
func (m *GetBookResponse) String() string { return proto.CompactTextString(m) }
func (*GetBookResponse) ProtoMessage()    {}
func (*GetBookResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_14fbc13de7c38f78, []int{4}
}

func (m *GetBookResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetBookResponse.Unmarshal(m, b)
}
func (m *GetBookResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetBookResponse.Marshal(b, m, deterministic)
}
func (m *GetBookResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetBookResponse.Merge(m, src)
}
func (m *GetBookResponse) XXX_Size() int {
	return xxx_messageInfo_GetBookResponse.Size(m)
}
func (m *GetBookResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetBookResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetBookResponse proto.InternalMessageInfo

func (m *GetBookResponse) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *GetBookResponse) GetDetail() string {
	if m != nil {
		return m.Detail
	}
	return ""
}

func (m *GetBookResponse) GetBook() *Book {
	if m != nil {
		return m.Book
	}
	return nil
}

type GetMultipleBookRequest struct {
	Id                   []string `protobuf:"bytes,1,rep,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetMultipleBookRequest) Reset()         { *m = GetMultipleBookRequest{} }
func (m *GetMultipleBookRequest) String() string { return proto.CompactTextString(m) }
func (*GetMultipleBookRequest) ProtoMessage()    {}
func (*GetMultipleBookRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_14fbc13de7c38f78, []int{5}
}

func (m *GetMultipleBookRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetMultipleBookRequest.Unmarshal(m, b)
}
func (m *GetMultipleBookRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetMultipleBookRequest.Marshal(b, m, deterministic)
}
func (m *GetMultipleBookRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetMultipleBookRequest.Merge(m, src)
}
func (m *GetMultipleBookRequest) XXX_Size() int {
	return xxx_messageInfo_GetMultipleBookRequest.Size(m)
}
func (m *GetMultipleBookRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetMultipleBookRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetMultipleBookRequest proto.InternalMessageInfo

func (m *GetMultipleBookRequest) GetId() []string {
	if m != nil {
		return m.Id
	}
	return nil
}

type GetMultipleBookResponse struct {
	Code                 int32    `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Detail               string   `protobuf:"bytes,2,opt,name=detail,proto3" json:"detail,omitempty"`
	Books                []*Book  `protobuf:"bytes,3,rep,name=books,proto3" json:"books,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetMultipleBookResponse) Reset()         { *m = GetMultipleBookResponse{} }
func (m *GetMultipleBookResponse) String() string { return proto.CompactTextString(m) }
func (*GetMultipleBookResponse) ProtoMessage()    {}
func (*GetMultipleBookResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_14fbc13de7c38f78, []int{6}
}

func (m *GetMultipleBookResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetMultipleBookResponse.Unmarshal(m, b)
}
func (m *GetMultipleBookResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetMultipleBookResponse.Marshal(b, m, deterministic)
}
func (m *GetMultipleBookResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetMultipleBookResponse.Merge(m, src)
}
func (m *GetMultipleBookResponse) XXX_Size() int {
	return xxx_messageInfo_GetMultipleBookResponse.Size(m)
}
func (m *GetMultipleBookResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetMultipleBookResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetMultipleBookResponse proto.InternalMessageInfo

func (m *GetMultipleBookResponse) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *GetMultipleBookResponse) GetDetail() string {
	if m != nil {
		return m.Detail
	}
	return ""
}

func (m *GetMultipleBookResponse) GetBooks() []*Book {
	if m != nil {
		return m.Books
	}
	return nil
}

type ListBookRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListBookRequest) Reset()         { *m = ListBookRequest{} }
func (m *ListBookRequest) String() string { return proto.CompactTextString(m) }
func (*ListBookRequest) ProtoMessage()    {}
func (*ListBookRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_14fbc13de7c38f78, []int{7}
}

func (m *ListBookRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListBookRequest.Unmarshal(m, b)
}
func (m *ListBookRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListBookRequest.Marshal(b, m, deterministic)
}
func (m *ListBookRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListBookRequest.Merge(m, src)
}
func (m *ListBookRequest) XXX_Size() int {
	return xxx_messageInfo_ListBookRequest.Size(m)
}
func (m *ListBookRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListBookRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListBookRequest proto.InternalMessageInfo

type ListBookResponse struct {
	Code                 int32    `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Detail               string   `protobuf:"bytes,2,opt,name=detail,proto3" json:"detail,omitempty"`
	Books                []*Book  `protobuf:"bytes,3,rep,name=books,proto3" json:"books,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListBookResponse) Reset()         { *m = ListBookResponse{} }
func (m *ListBookResponse) String() string { return proto.CompactTextString(m) }
func (*ListBookResponse) ProtoMessage()    {}
func (*ListBookResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_14fbc13de7c38f78, []int{8}
}

func (m *ListBookResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListBookResponse.Unmarshal(m, b)
}
func (m *ListBookResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListBookResponse.Marshal(b, m, deterministic)
}
func (m *ListBookResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListBookResponse.Merge(m, src)
}
func (m *ListBookResponse) XXX_Size() int {
	return xxx_messageInfo_ListBookResponse.Size(m)
}
func (m *ListBookResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListBookResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListBookResponse proto.InternalMessageInfo

func (m *ListBookResponse) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *ListBookResponse) GetDetail() string {
	if m != nil {
		return m.Detail
	}
	return ""
}

func (m *ListBookResponse) GetBooks() []*Book {
	if m != nil {
		return m.Books
	}
	return nil
}

type UpdateBookRequest struct {
	Book                 *Book    `protobuf:"bytes,1,opt,name=book,proto3" json:"book,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateBookRequest) Reset()         { *m = UpdateBookRequest{} }
func (m *UpdateBookRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateBookRequest) ProtoMessage()    {}
func (*UpdateBookRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_14fbc13de7c38f78, []int{9}
}

func (m *UpdateBookRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateBookRequest.Unmarshal(m, b)
}
func (m *UpdateBookRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateBookRequest.Marshal(b, m, deterministic)
}
func (m *UpdateBookRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateBookRequest.Merge(m, src)
}
func (m *UpdateBookRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateBookRequest.Size(m)
}
func (m *UpdateBookRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateBookRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateBookRequest proto.InternalMessageInfo

func (m *UpdateBookRequest) GetBook() *Book {
	if m != nil {
		return m.Book
	}
	return nil
}

type UpdateBookResponse struct {
	Code                 int32    `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Detail               string   `protobuf:"bytes,2,opt,name=detail,proto3" json:"detail,omitempty"`
	Book                 *Book    `protobuf:"bytes,3,opt,name=book,proto3" json:"book,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateBookResponse) Reset()         { *m = UpdateBookResponse{} }
func (m *UpdateBookResponse) String() string { return proto.CompactTextString(m) }
func (*UpdateBookResponse) ProtoMessage()    {}
func (*UpdateBookResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_14fbc13de7c38f78, []int{10}
}

func (m *UpdateBookResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateBookResponse.Unmarshal(m, b)
}
func (m *UpdateBookResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateBookResponse.Marshal(b, m, deterministic)
}
func (m *UpdateBookResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateBookResponse.Merge(m, src)
}
func (m *UpdateBookResponse) XXX_Size() int {
	return xxx_messageInfo_UpdateBookResponse.Size(m)
}
func (m *UpdateBookResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateBookResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateBookResponse proto.InternalMessageInfo

func (m *UpdateBookResponse) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *UpdateBookResponse) GetDetail() string {
	if m != nil {
		return m.Detail
	}
	return ""
}

func (m *UpdateBookResponse) GetBook() *Book {
	if m != nil {
		return m.Book
	}
	return nil
}

type DeleteBookRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteBookRequest) Reset()         { *m = DeleteBookRequest{} }
func (m *DeleteBookRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteBookRequest) ProtoMessage()    {}
func (*DeleteBookRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_14fbc13de7c38f78, []int{11}
}

func (m *DeleteBookRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteBookRequest.Unmarshal(m, b)
}
func (m *DeleteBookRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteBookRequest.Marshal(b, m, deterministic)
}
func (m *DeleteBookRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteBookRequest.Merge(m, src)
}
func (m *DeleteBookRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteBookRequest.Size(m)
}
func (m *DeleteBookRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteBookRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteBookRequest proto.InternalMessageInfo

func (m *DeleteBookRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type DeleteBookResponse struct {
	Code                 int32    `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Detail               string   `protobuf:"bytes,2,opt,name=detail,proto3" json:"detail,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteBookResponse) Reset()         { *m = DeleteBookResponse{} }
func (m *DeleteBookResponse) String() string { return proto.CompactTextString(m) }
func (*DeleteBookResponse) ProtoMessage()    {}
func (*DeleteBookResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_14fbc13de7c38f78, []int{12}
}

func (m *DeleteBookResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteBookResponse.Unmarshal(m, b)
}
func (m *DeleteBookResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteBookResponse.Marshal(b, m, deterministic)
}
func (m *DeleteBookResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteBookResponse.Merge(m, src)
}
func (m *DeleteBookResponse) XXX_Size() int {
	return xxx_messageInfo_DeleteBookResponse.Size(m)
}
func (m *DeleteBookResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteBookResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteBookResponse proto.InternalMessageInfo

func (m *DeleteBookResponse) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *DeleteBookResponse) GetDetail() string {
	if m != nil {
		return m.Detail
	}
	return ""
}

type SearchBookRequest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SearchBookRequest) Reset()         { *m = SearchBookRequest{} }
func (m *SearchBookRequest) String() string { return proto.CompactTextString(m) }
func (*SearchBookRequest) ProtoMessage()    {}
func (*SearchBookRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_14fbc13de7c38f78, []int{13}
}

func (m *SearchBookRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SearchBookRequest.Unmarshal(m, b)
}
func (m *SearchBookRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SearchBookRequest.Marshal(b, m, deterministic)
}
func (m *SearchBookRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SearchBookRequest.Merge(m, src)
}
func (m *SearchBookRequest) XXX_Size() int {
	return xxx_messageInfo_SearchBookRequest.Size(m)
}
func (m *SearchBookRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SearchBookRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SearchBookRequest proto.InternalMessageInfo

func (m *SearchBookRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type SearchBookResponse struct {
	Code                 int32    `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Detail               string   `protobuf:"bytes,2,opt,name=detail,proto3" json:"detail,omitempty"`
	Books                []*Book  `protobuf:"bytes,3,rep,name=books,proto3" json:"books,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SearchBookResponse) Reset()         { *m = SearchBookResponse{} }
func (m *SearchBookResponse) String() string { return proto.CompactTextString(m) }
func (*SearchBookResponse) ProtoMessage()    {}
func (*SearchBookResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_14fbc13de7c38f78, []int{14}
}

func (m *SearchBookResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SearchBookResponse.Unmarshal(m, b)
}
func (m *SearchBookResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SearchBookResponse.Marshal(b, m, deterministic)
}
func (m *SearchBookResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SearchBookResponse.Merge(m, src)
}
func (m *SearchBookResponse) XXX_Size() int {
	return xxx_messageInfo_SearchBookResponse.Size(m)
}
func (m *SearchBookResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SearchBookResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SearchBookResponse proto.InternalMessageInfo

func (m *SearchBookResponse) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *SearchBookResponse) GetDetail() string {
	if m != nil {
		return m.Detail
	}
	return ""
}

func (m *SearchBookResponse) GetBooks() []*Book {
	if m != nil {
		return m.Books
	}
	return nil
}

func init() {
	proto.RegisterType((*Book)(nil), "go.micro.bookstore.srv.product.Book")
	proto.RegisterType((*CreateBookRequest)(nil), "go.micro.bookstore.srv.product.CreateBookRequest")
	proto.RegisterType((*CreateBookResponse)(nil), "go.micro.bookstore.srv.product.CreateBookResponse")
	proto.RegisterType((*GetBookRequest)(nil), "go.micro.bookstore.srv.product.GetBookRequest")
	proto.RegisterType((*GetBookResponse)(nil), "go.micro.bookstore.srv.product.GetBookResponse")
	proto.RegisterType((*GetMultipleBookRequest)(nil), "go.micro.bookstore.srv.product.GetMultipleBookRequest")
	proto.RegisterType((*GetMultipleBookResponse)(nil), "go.micro.bookstore.srv.product.GetMultipleBookResponse")
	proto.RegisterType((*ListBookRequest)(nil), "go.micro.bookstore.srv.product.ListBookRequest")
	proto.RegisterType((*ListBookResponse)(nil), "go.micro.bookstore.srv.product.ListBookResponse")
	proto.RegisterType((*UpdateBookRequest)(nil), "go.micro.bookstore.srv.product.UpdateBookRequest")
	proto.RegisterType((*UpdateBookResponse)(nil), "go.micro.bookstore.srv.product.UpdateBookResponse")
	proto.RegisterType((*DeleteBookRequest)(nil), "go.micro.bookstore.srv.product.DeleteBookRequest")
	proto.RegisterType((*DeleteBookResponse)(nil), "go.micro.bookstore.srv.product.DeleteBookResponse")
	proto.RegisterType((*SearchBookRequest)(nil), "go.micro.bookstore.srv.product.SearchBookRequest")
	proto.RegisterType((*SearchBookResponse)(nil), "go.micro.bookstore.srv.product.SearchBookResponse")
}

func init() { proto.RegisterFile("proto/product/product.proto", fileDescriptor_14fbc13de7c38f78) }

var fileDescriptor_14fbc13de7c38f78 = []byte{
	// 584 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xbc, 0x56, 0xdd, 0x6a, 0x13, 0x41,
	0x14, 0xee, 0x66, 0xf3, 0x7b, 0x22, 0xad, 0x39, 0x48, 0x5d, 0x52, 0xd4, 0x38, 0x16, 0xcc, 0xd5,
	0x56, 0x23, 0xa8, 0x78, 0x65, 0x55, 0x28, 0x82, 0x11, 0x89, 0x78, 0x1d, 0xb6, 0x3b, 0x83, 0x1d,
	0xba, 0xcd, 0xac, 0xb3, 0xb3, 0x15, 0x8b, 0x37, 0x82, 0xef, 0xe0, 0x43, 0xf9, 0x52, 0x92, 0x99,
	0xfd, 0xab, 0x5b, 0x9c, 0x44, 0x4a, 0xae, 0xb2, 0xf3, 0x9d, 0x9f, 0xef, 0xcc, 0x99, 0xf3, 0x1d,
	0x02, 0x7b, 0xb1, 0x14, 0x4a, 0x1c, 0xc4, 0x52, 0xd0, 0x34, 0x54, 0xf9, 0xaf, 0xaf, 0x51, 0xbc,
	0xfb, 0x59, 0xf8, 0x67, 0x3c, 0x94, 0xc2, 0x3f, 0x16, 0xe2, 0x34, 0x51, 0x42, 0x32, 0x3f, 0x91,
	0xe7, 0x7e, 0xe6, 0x45, 0x7e, 0x35, 0xa0, 0xf9, 0x4a, 0x88, 0x53, 0xdc, 0x86, 0x06, 0xa7, 0x9e,
	0x33, 0x72, 0xc6, 0xbd, 0x59, 0x83, 0x53, 0x44, 0x68, 0x2e, 0x82, 0x33, 0xe6, 0x35, 0x34, 0xa2,
	0xbf, 0xf1, 0x3e, 0xdc, 0xa0, 0x3c, 0x89, 0xa3, 0xe0, 0xdb, 0x5c, 0xdb, 0x5c, 0x6d, 0xeb, 0x67,
	0xd8, 0xfb, 0xa5, 0xcb, 0x08, 0xfa, 0x94, 0x25, 0xa1, 0xe4, 0xb1, 0xe2, 0x62, 0xe1, 0x35, 0x33,
	0x8f, 0x12, 0xc2, 0x5b, 0xd0, 0x0a, 0xc5, 0x39, 0x93, 0x5e, 0x4b, 0xdb, 0xcc, 0x01, 0xf7, 0xa0,
	0x17, 0xa4, 0xea, 0x44, 0xc8, 0x39, 0xa7, 0x5e, 0x5b, 0x5b, 0xba, 0x06, 0x78, 0x4b, 0x97, 0x21,
	0xb1, 0xe4, 0x21, 0xf3, 0x3a, 0x23, 0x67, 0xec, 0xcc, 0xcc, 0x01, 0xef, 0x41, 0x5f, 0xb2, 0x88,
	0x05, 0x09, 0xa3, 0xf3, 0x40, 0x79, 0xdd, 0x91, 0x33, 0x76, 0x67, 0x90, 0x43, 0x87, 0x0a, 0xef,
	0x00, 0x84, 0x92, 0x05, 0xca, 0xd8, 0x7b, 0xda, 0xde, 0xcb, 0x10, 0x63, 0x4e, 0x63, 0x9a, 0x9b,
	0xc1, 0x98, 0x33, 0xe4, 0x50, 0x91, 0x29, 0x0c, 0x5e, 0x6b, 0xdf, 0x65, 0x7b, 0x66, 0xec, 0x4b,
	0xca, 0x12, 0x85, 0xcf, 0xa1, 0xb9, 0xec, 0xa3, 0xee, 0x53, 0x7f, 0xb2, 0xef, 0xff, 0xbb, 0xbb,
	0xbe, 0x0e, 0xd5, 0x11, 0xe4, 0x02, 0xb0, 0x9a, 0x2e, 0x89, 0xc5, 0x22, 0x61, 0xcb, 0x2e, 0x87,
	0x82, 0x32, 0x9d, 0xaf, 0x35, 0xd3, 0xdf, 0xb8, 0x0b, 0x6d, 0xca, 0x54, 0xc0, 0xa3, 0xac, 0xf7,
	0xd9, 0xa9, 0xe0, 0x76, 0xd7, 0xe6, 0xde, 0x87, 0xed, 0x23, 0xa6, 0xaa, 0xf7, 0xc8, 0x5f, 0xd7,
	0x29, 0x5f, 0x97, 0x7c, 0x85, 0x9d, 0xc2, 0x6b, 0xa3, 0xe5, 0x8d, 0x61, 0xf7, 0x88, 0xa9, 0x69,
	0x1a, 0x29, 0x1e, 0x47, 0x97, 0xda, 0x9d, 0x0f, 0xa5, 0x6b, 0x86, 0x92, 0xfc, 0x70, 0xe0, 0x76,
	0xcd, 0xf5, 0x3f, 0x6a, 0x7d, 0x01, 0x2d, 0x5d, 0x95, 0xe7, 0x8e, 0xdc, 0x95, 0x8b, 0x35, 0x21,
	0x64, 0x00, 0x3b, 0xef, 0x78, 0x52, 0xed, 0x26, 0xb9, 0x80, 0x9b, 0x25, 0xb4, 0xe1, 0x72, 0xa6,
	0x30, 0xf8, 0xa4, 0x67, 0xf6, 0xda, 0xc6, 0xb4, 0x9a, 0x6e, 0xa3, 0x73, 0xf0, 0x00, 0x06, 0x6f,
	0x58, 0xc4, 0xd4, 0x95, 0x23, 0x90, 0xed, 0x25, 0xf2, 0x12, 0xb0, 0xea, 0xb4, 0x7e, 0x81, 0xe4,
	0x21, 0x0c, 0x3e, 0xb2, 0x40, 0x86, 0x27, 0x36, 0x41, 0x7c, 0x07, 0xac, 0x3a, 0x6e, 0xf6, 0x61,
	0x27, 0xbf, 0xdb, 0xd0, 0xf9, 0x60, 0x70, 0x4c, 0x01, 0xca, 0xe5, 0x81, 0x8f, 0x6d, 0x69, 0x6a,
	0x7b, 0x6b, 0x38, 0x59, 0x27, 0xc4, 0x5c, 0x94, 0x6c, 0x61, 0x04, 0x9d, 0x6c, 0x23, 0xa0, 0x6f,
	0x4b, 0x70, 0x79, 0xc1, 0x0c, 0x0f, 0x56, 0xf6, 0x2f, 0xd8, 0x7e, 0x3a, 0x7a, 0x01, 0x55, 0xc5,
	0x8d, 0x4f, 0x57, 0x48, 0x73, 0xc5, 0xe2, 0x18, 0x3e, 0x5b, 0x3b, 0xae, 0x28, 0x43, 0x40, 0x37,
	0x17, 0x33, 0x5a, 0x6f, 0xf1, 0xd7, 0x26, 0x18, 0x3e, 0x5a, 0x3d, 0xa0, 0x20, 0x4c, 0x01, 0x4a,
	0xc9, 0xd9, 0x1f, 0xb7, 0xa6, 0x76, 0xfb, 0xe3, 0xd6, 0x15, 0x6d, 0x68, 0x4b, 0x21, 0xd9, 0x69,
	0x6b, 0xca, 0xb4, 0xd3, 0xd6, 0x75, 0x6a, 0x68, 0x4b, 0x51, 0xd9, 0x69, 0x6b, 0x4a, 0xb5, 0xd3,
	0xd6, 0x35, 0x4b, 0xb6, 0x8e, 0xdb, 0xfa, 0xef, 0xd0, 0x93, 0x3f, 0x01, 0x00, 0x00, 0xff, 0xff,
	0xd2, 0xb5, 0x6a, 0xec, 0x2d, 0x09, 0x00, 0x00,
}
