// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/catalog/catalog.proto

package go_micro_bookstore_srv_catalog

import (
	fmt "fmt"
	product "github.com/ahmadnurus/go-micro-bookstore/product/srv/proto/product"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Category struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	DisplayName          string   `protobuf:"bytes,3,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	Books                []string `protobuf:"bytes,4,rep,name=books,proto3" json:"books,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Category) Reset()         { *m = Category{} }
func (m *Category) String() string { return proto.CompactTextString(m) }
func (*Category) ProtoMessage()    {}
func (*Category) Descriptor() ([]byte, []int) {
	return fileDescriptor_0212cf3dccdf82e6, []int{0}
}

func (m *Category) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Category.Unmarshal(m, b)
}
func (m *Category) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Category.Marshal(b, m, deterministic)
}
func (m *Category) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Category.Merge(m, src)
}
func (m *Category) XXX_Size() int {
	return xxx_messageInfo_Category.Size(m)
}
func (m *Category) XXX_DiscardUnknown() {
	xxx_messageInfo_Category.DiscardUnknown(m)
}

var xxx_messageInfo_Category proto.InternalMessageInfo

func (m *Category) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Category) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Category) GetDisplayName() string {
	if m != nil {
		return m.DisplayName
	}
	return ""
}

func (m *Category) GetBooks() []string {
	if m != nil {
		return m.Books
	}
	return nil
}

type CreateCategoryRequest struct {
	Category             *Category `protobuf:"bytes,1,opt,name=category,proto3" json:"category,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *CreateCategoryRequest) Reset()         { *m = CreateCategoryRequest{} }
func (m *CreateCategoryRequest) String() string { return proto.CompactTextString(m) }
func (*CreateCategoryRequest) ProtoMessage()    {}
func (*CreateCategoryRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_0212cf3dccdf82e6, []int{1}
}

func (m *CreateCategoryRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateCategoryRequest.Unmarshal(m, b)
}
func (m *CreateCategoryRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateCategoryRequest.Marshal(b, m, deterministic)
}
func (m *CreateCategoryRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateCategoryRequest.Merge(m, src)
}
func (m *CreateCategoryRequest) XXX_Size() int {
	return xxx_messageInfo_CreateCategoryRequest.Size(m)
}
func (m *CreateCategoryRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateCategoryRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateCategoryRequest proto.InternalMessageInfo

func (m *CreateCategoryRequest) GetCategory() *Category {
	if m != nil {
		return m.Category
	}
	return nil
}

type CreateCategoryResponse struct {
	Code                 int32     `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Detail               string    `protobuf:"bytes,2,opt,name=detail,proto3" json:"detail,omitempty"`
	Category             *Category `protobuf:"bytes,3,opt,name=category,proto3" json:"category,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *CreateCategoryResponse) Reset()         { *m = CreateCategoryResponse{} }
func (m *CreateCategoryResponse) String() string { return proto.CompactTextString(m) }
func (*CreateCategoryResponse) ProtoMessage()    {}
func (*CreateCategoryResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_0212cf3dccdf82e6, []int{2}
}

func (m *CreateCategoryResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateCategoryResponse.Unmarshal(m, b)
}
func (m *CreateCategoryResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateCategoryResponse.Marshal(b, m, deterministic)
}
func (m *CreateCategoryResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateCategoryResponse.Merge(m, src)
}
func (m *CreateCategoryResponse) XXX_Size() int {
	return xxx_messageInfo_CreateCategoryResponse.Size(m)
}
func (m *CreateCategoryResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateCategoryResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateCategoryResponse proto.InternalMessageInfo

func (m *CreateCategoryResponse) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *CreateCategoryResponse) GetDetail() string {
	if m != nil {
		return m.Detail
	}
	return ""
}

func (m *CreateCategoryResponse) GetCategory() *Category {
	if m != nil {
		return m.Category
	}
	return nil
}

type GetCategoryRequest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetCategoryRequest) Reset()         { *m = GetCategoryRequest{} }
func (m *GetCategoryRequest) String() string { return proto.CompactTextString(m) }
func (*GetCategoryRequest) ProtoMessage()    {}
func (*GetCategoryRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_0212cf3dccdf82e6, []int{3}
}

func (m *GetCategoryRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetCategoryRequest.Unmarshal(m, b)
}
func (m *GetCategoryRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetCategoryRequest.Marshal(b, m, deterministic)
}
func (m *GetCategoryRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetCategoryRequest.Merge(m, src)
}
func (m *GetCategoryRequest) XXX_Size() int {
	return xxx_messageInfo_GetCategoryRequest.Size(m)
}
func (m *GetCategoryRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetCategoryRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetCategoryRequest proto.InternalMessageInfo

func (m *GetCategoryRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type GetCategoryResponse struct {
	Code                 int32     `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Detail               string    `protobuf:"bytes,2,opt,name=detail,proto3" json:"detail,omitempty"`
	Category             *Category `protobuf:"bytes,3,opt,name=category,proto3" json:"category,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *GetCategoryResponse) Reset()         { *m = GetCategoryResponse{} }
func (m *GetCategoryResponse) String() string { return proto.CompactTextString(m) }
func (*GetCategoryResponse) ProtoMessage()    {}
func (*GetCategoryResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_0212cf3dccdf82e6, []int{4}
}

func (m *GetCategoryResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetCategoryResponse.Unmarshal(m, b)
}
func (m *GetCategoryResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetCategoryResponse.Marshal(b, m, deterministic)
}
func (m *GetCategoryResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetCategoryResponse.Merge(m, src)
}
func (m *GetCategoryResponse) XXX_Size() int {
	return xxx_messageInfo_GetCategoryResponse.Size(m)
}
func (m *GetCategoryResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetCategoryResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetCategoryResponse proto.InternalMessageInfo

func (m *GetCategoryResponse) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *GetCategoryResponse) GetDetail() string {
	if m != nil {
		return m.Detail
	}
	return ""
}

func (m *GetCategoryResponse) GetCategory() *Category {
	if m != nil {
		return m.Category
	}
	return nil
}

type ListCategoryRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListCategoryRequest) Reset()         { *m = ListCategoryRequest{} }
func (m *ListCategoryRequest) String() string { return proto.CompactTextString(m) }
func (*ListCategoryRequest) ProtoMessage()    {}
func (*ListCategoryRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_0212cf3dccdf82e6, []int{5}
}

func (m *ListCategoryRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListCategoryRequest.Unmarshal(m, b)
}
func (m *ListCategoryRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListCategoryRequest.Marshal(b, m, deterministic)
}
func (m *ListCategoryRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListCategoryRequest.Merge(m, src)
}
func (m *ListCategoryRequest) XXX_Size() int {
	return xxx_messageInfo_ListCategoryRequest.Size(m)
}
func (m *ListCategoryRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListCategoryRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListCategoryRequest proto.InternalMessageInfo

type ListCategoryResponse struct {
	Code                 int32       `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Detail               string      `protobuf:"bytes,2,opt,name=detail,proto3" json:"detail,omitempty"`
	Categories           []*Category `protobuf:"bytes,3,rep,name=categories,proto3" json:"categories,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *ListCategoryResponse) Reset()         { *m = ListCategoryResponse{} }
func (m *ListCategoryResponse) String() string { return proto.CompactTextString(m) }
func (*ListCategoryResponse) ProtoMessage()    {}
func (*ListCategoryResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_0212cf3dccdf82e6, []int{6}
}

func (m *ListCategoryResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListCategoryResponse.Unmarshal(m, b)
}
func (m *ListCategoryResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListCategoryResponse.Marshal(b, m, deterministic)
}
func (m *ListCategoryResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListCategoryResponse.Merge(m, src)
}
func (m *ListCategoryResponse) XXX_Size() int {
	return xxx_messageInfo_ListCategoryResponse.Size(m)
}
func (m *ListCategoryResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListCategoryResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListCategoryResponse proto.InternalMessageInfo

func (m *ListCategoryResponse) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *ListCategoryResponse) GetDetail() string {
	if m != nil {
		return m.Detail
	}
	return ""
}

func (m *ListCategoryResponse) GetCategories() []*Category {
	if m != nil {
		return m.Categories
	}
	return nil
}

type UpdateCategoryRequest struct {
	Category             *Category `protobuf:"bytes,1,opt,name=category,proto3" json:"category,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *UpdateCategoryRequest) Reset()         { *m = UpdateCategoryRequest{} }
func (m *UpdateCategoryRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateCategoryRequest) ProtoMessage()    {}
func (*UpdateCategoryRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_0212cf3dccdf82e6, []int{7}
}

func (m *UpdateCategoryRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateCategoryRequest.Unmarshal(m, b)
}
func (m *UpdateCategoryRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateCategoryRequest.Marshal(b, m, deterministic)
}
func (m *UpdateCategoryRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateCategoryRequest.Merge(m, src)
}
func (m *UpdateCategoryRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateCategoryRequest.Size(m)
}
func (m *UpdateCategoryRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateCategoryRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateCategoryRequest proto.InternalMessageInfo

func (m *UpdateCategoryRequest) GetCategory() *Category {
	if m != nil {
		return m.Category
	}
	return nil
}

type UpdateCategoryResponse struct {
	Code                 int32     `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Detail               string    `protobuf:"bytes,2,opt,name=detail,proto3" json:"detail,omitempty"`
	Category             *Category `protobuf:"bytes,3,opt,name=category,proto3" json:"category,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *UpdateCategoryResponse) Reset()         { *m = UpdateCategoryResponse{} }
func (m *UpdateCategoryResponse) String() string { return proto.CompactTextString(m) }
func (*UpdateCategoryResponse) ProtoMessage()    {}
func (*UpdateCategoryResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_0212cf3dccdf82e6, []int{8}
}

func (m *UpdateCategoryResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateCategoryResponse.Unmarshal(m, b)
}
func (m *UpdateCategoryResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateCategoryResponse.Marshal(b, m, deterministic)
}
func (m *UpdateCategoryResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateCategoryResponse.Merge(m, src)
}
func (m *UpdateCategoryResponse) XXX_Size() int {
	return xxx_messageInfo_UpdateCategoryResponse.Size(m)
}
func (m *UpdateCategoryResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateCategoryResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateCategoryResponse proto.InternalMessageInfo

func (m *UpdateCategoryResponse) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *UpdateCategoryResponse) GetDetail() string {
	if m != nil {
		return m.Detail
	}
	return ""
}

func (m *UpdateCategoryResponse) GetCategory() *Category {
	if m != nil {
		return m.Category
	}
	return nil
}

type DeleteCategoryRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteCategoryRequest) Reset()         { *m = DeleteCategoryRequest{} }
func (m *DeleteCategoryRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteCategoryRequest) ProtoMessage()    {}
func (*DeleteCategoryRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_0212cf3dccdf82e6, []int{9}
}

func (m *DeleteCategoryRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteCategoryRequest.Unmarshal(m, b)
}
func (m *DeleteCategoryRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteCategoryRequest.Marshal(b, m, deterministic)
}
func (m *DeleteCategoryRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteCategoryRequest.Merge(m, src)
}
func (m *DeleteCategoryRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteCategoryRequest.Size(m)
}
func (m *DeleteCategoryRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteCategoryRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteCategoryRequest proto.InternalMessageInfo

func (m *DeleteCategoryRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type DeleteCategoryResponse struct {
	Code                 int32    `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Detail               string   `protobuf:"bytes,2,opt,name=detail,proto3" json:"detail,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteCategoryResponse) Reset()         { *m = DeleteCategoryResponse{} }
func (m *DeleteCategoryResponse) String() string { return proto.CompactTextString(m) }
func (*DeleteCategoryResponse) ProtoMessage()    {}
func (*DeleteCategoryResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_0212cf3dccdf82e6, []int{10}
}

func (m *DeleteCategoryResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteCategoryResponse.Unmarshal(m, b)
}
func (m *DeleteCategoryResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteCategoryResponse.Marshal(b, m, deterministic)
}
func (m *DeleteCategoryResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteCategoryResponse.Merge(m, src)
}
func (m *DeleteCategoryResponse) XXX_Size() int {
	return xxx_messageInfo_DeleteCategoryResponse.Size(m)
}
func (m *DeleteCategoryResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteCategoryResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteCategoryResponse proto.InternalMessageInfo

func (m *DeleteCategoryResponse) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *DeleteCategoryResponse) GetDetail() string {
	if m != nil {
		return m.Detail
	}
	return ""
}

type AddBookRequest struct {
	Category             string   `protobuf:"bytes,1,opt,name=category,proto3" json:"category,omitempty"`
	BookId               string   `protobuf:"bytes,2,opt,name=book_id,json=bookId,proto3" json:"book_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddBookRequest) Reset()         { *m = AddBookRequest{} }
func (m *AddBookRequest) String() string { return proto.CompactTextString(m) }
func (*AddBookRequest) ProtoMessage()    {}
func (*AddBookRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_0212cf3dccdf82e6, []int{11}
}

func (m *AddBookRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddBookRequest.Unmarshal(m, b)
}
func (m *AddBookRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddBookRequest.Marshal(b, m, deterministic)
}
func (m *AddBookRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddBookRequest.Merge(m, src)
}
func (m *AddBookRequest) XXX_Size() int {
	return xxx_messageInfo_AddBookRequest.Size(m)
}
func (m *AddBookRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AddBookRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AddBookRequest proto.InternalMessageInfo

func (m *AddBookRequest) GetCategory() string {
	if m != nil {
		return m.Category
	}
	return ""
}

func (m *AddBookRequest) GetBookId() string {
	if m != nil {
		return m.BookId
	}
	return ""
}

type AddBookResponse struct {
	Code                 int32    `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Detail               string   `protobuf:"bytes,2,opt,name=detail,proto3" json:"detail,omitempty"`
	Category             string   `protobuf:"bytes,3,opt,name=category,proto3" json:"category,omitempty"`
	BookId               string   `protobuf:"bytes,4,opt,name=book_id,json=bookId,proto3" json:"book_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddBookResponse) Reset()         { *m = AddBookResponse{} }
func (m *AddBookResponse) String() string { return proto.CompactTextString(m) }
func (*AddBookResponse) ProtoMessage()    {}
func (*AddBookResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_0212cf3dccdf82e6, []int{12}
}

func (m *AddBookResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddBookResponse.Unmarshal(m, b)
}
func (m *AddBookResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddBookResponse.Marshal(b, m, deterministic)
}
func (m *AddBookResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddBookResponse.Merge(m, src)
}
func (m *AddBookResponse) XXX_Size() int {
	return xxx_messageInfo_AddBookResponse.Size(m)
}
func (m *AddBookResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AddBookResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AddBookResponse proto.InternalMessageInfo

func (m *AddBookResponse) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *AddBookResponse) GetDetail() string {
	if m != nil {
		return m.Detail
	}
	return ""
}

func (m *AddBookResponse) GetCategory() string {
	if m != nil {
		return m.Category
	}
	return ""
}

func (m *AddBookResponse) GetBookId() string {
	if m != nil {
		return m.BookId
	}
	return ""
}

type GetByBookRequest struct {
	BookId               string   `protobuf:"bytes,1,opt,name=book_id,json=bookId,proto3" json:"book_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetByBookRequest) Reset()         { *m = GetByBookRequest{} }
func (m *GetByBookRequest) String() string { return proto.CompactTextString(m) }
func (*GetByBookRequest) ProtoMessage()    {}
func (*GetByBookRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_0212cf3dccdf82e6, []int{13}
}

func (m *GetByBookRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetByBookRequest.Unmarshal(m, b)
}
func (m *GetByBookRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetByBookRequest.Marshal(b, m, deterministic)
}
func (m *GetByBookRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetByBookRequest.Merge(m, src)
}
func (m *GetByBookRequest) XXX_Size() int {
	return xxx_messageInfo_GetByBookRequest.Size(m)
}
func (m *GetByBookRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetByBookRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetByBookRequest proto.InternalMessageInfo

func (m *GetByBookRequest) GetBookId() string {
	if m != nil {
		return m.BookId
	}
	return ""
}

type GetByBookResponse struct {
	Code                 int32     `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Detail               string    `protobuf:"bytes,2,opt,name=detail,proto3" json:"detail,omitempty"`
	Category             *Category `protobuf:"bytes,3,opt,name=category,proto3" json:"category,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *GetByBookResponse) Reset()         { *m = GetByBookResponse{} }
func (m *GetByBookResponse) String() string { return proto.CompactTextString(m) }
func (*GetByBookResponse) ProtoMessage()    {}
func (*GetByBookResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_0212cf3dccdf82e6, []int{14}
}

func (m *GetByBookResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetByBookResponse.Unmarshal(m, b)
}
func (m *GetByBookResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetByBookResponse.Marshal(b, m, deterministic)
}
func (m *GetByBookResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetByBookResponse.Merge(m, src)
}
func (m *GetByBookResponse) XXX_Size() int {
	return xxx_messageInfo_GetByBookResponse.Size(m)
}
func (m *GetByBookResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetByBookResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetByBookResponse proto.InternalMessageInfo

func (m *GetByBookResponse) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *GetByBookResponse) GetDetail() string {
	if m != nil {
		return m.Detail
	}
	return ""
}

func (m *GetByBookResponse) GetCategory() *Category {
	if m != nil {
		return m.Category
	}
	return nil
}

type ListBookRequest struct {
	Category             string   `protobuf:"bytes,1,opt,name=category,proto3" json:"category,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListBookRequest) Reset()         { *m = ListBookRequest{} }
func (m *ListBookRequest) String() string { return proto.CompactTextString(m) }
func (*ListBookRequest) ProtoMessage()    {}
func (*ListBookRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_0212cf3dccdf82e6, []int{15}
}

func (m *ListBookRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListBookRequest.Unmarshal(m, b)
}
func (m *ListBookRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListBookRequest.Marshal(b, m, deterministic)
}
func (m *ListBookRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListBookRequest.Merge(m, src)
}
func (m *ListBookRequest) XXX_Size() int {
	return xxx_messageInfo_ListBookRequest.Size(m)
}
func (m *ListBookRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListBookRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListBookRequest proto.InternalMessageInfo

func (m *ListBookRequest) GetCategory() string {
	if m != nil {
		return m.Category
	}
	return ""
}

type ListBookResponse struct {
	Code                 int32           `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Detail               string          `protobuf:"bytes,2,opt,name=detail,proto3" json:"detail,omitempty"`
	Category             string          `protobuf:"bytes,3,opt,name=category,proto3" json:"category,omitempty"`
	Books                []*product.Book `protobuf:"bytes,4,rep,name=books,proto3" json:"books,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *ListBookResponse) Reset()         { *m = ListBookResponse{} }
func (m *ListBookResponse) String() string { return proto.CompactTextString(m) }
func (*ListBookResponse) ProtoMessage()    {}
func (*ListBookResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_0212cf3dccdf82e6, []int{16}
}

func (m *ListBookResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListBookResponse.Unmarshal(m, b)
}
func (m *ListBookResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListBookResponse.Marshal(b, m, deterministic)
}
func (m *ListBookResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListBookResponse.Merge(m, src)
}
func (m *ListBookResponse) XXX_Size() int {
	return xxx_messageInfo_ListBookResponse.Size(m)
}
func (m *ListBookResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListBookResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListBookResponse proto.InternalMessageInfo

func (m *ListBookResponse) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *ListBookResponse) GetDetail() string {
	if m != nil {
		return m.Detail
	}
	return ""
}

func (m *ListBookResponse) GetCategory() string {
	if m != nil {
		return m.Category
	}
	return ""
}

func (m *ListBookResponse) GetBooks() []*product.Book {
	if m != nil {
		return m.Books
	}
	return nil
}

type RemoveBookRequest struct {
	Category             string   `protobuf:"bytes,1,opt,name=category,proto3" json:"category,omitempty"`
	BookId               string   `protobuf:"bytes,2,opt,name=book_id,json=bookId,proto3" json:"book_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RemoveBookRequest) Reset()         { *m = RemoveBookRequest{} }
func (m *RemoveBookRequest) String() string { return proto.CompactTextString(m) }
func (*RemoveBookRequest) ProtoMessage()    {}
func (*RemoveBookRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_0212cf3dccdf82e6, []int{17}
}

func (m *RemoveBookRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RemoveBookRequest.Unmarshal(m, b)
}
func (m *RemoveBookRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RemoveBookRequest.Marshal(b, m, deterministic)
}
func (m *RemoveBookRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RemoveBookRequest.Merge(m, src)
}
func (m *RemoveBookRequest) XXX_Size() int {
	return xxx_messageInfo_RemoveBookRequest.Size(m)
}
func (m *RemoveBookRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RemoveBookRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RemoveBookRequest proto.InternalMessageInfo

func (m *RemoveBookRequest) GetCategory() string {
	if m != nil {
		return m.Category
	}
	return ""
}

func (m *RemoveBookRequest) GetBookId() string {
	if m != nil {
		return m.BookId
	}
	return ""
}

type RemoveBookResponse struct {
	Code                 int32    `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Detail               string   `protobuf:"bytes,2,opt,name=detail,proto3" json:"detail,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RemoveBookResponse) Reset()         { *m = RemoveBookResponse{} }
func (m *RemoveBookResponse) String() string { return proto.CompactTextString(m) }
func (*RemoveBookResponse) ProtoMessage()    {}
func (*RemoveBookResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_0212cf3dccdf82e6, []int{18}
}

func (m *RemoveBookResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RemoveBookResponse.Unmarshal(m, b)
}
func (m *RemoveBookResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RemoveBookResponse.Marshal(b, m, deterministic)
}
func (m *RemoveBookResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RemoveBookResponse.Merge(m, src)
}
func (m *RemoveBookResponse) XXX_Size() int {
	return xxx_messageInfo_RemoveBookResponse.Size(m)
}
func (m *RemoveBookResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RemoveBookResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RemoveBookResponse proto.InternalMessageInfo

func (m *RemoveBookResponse) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *RemoveBookResponse) GetDetail() string {
	if m != nil {
		return m.Detail
	}
	return ""
}

func init() {
	proto.RegisterType((*Category)(nil), "go.micro.bookstore.srv.catalog.Category")
	proto.RegisterType((*CreateCategoryRequest)(nil), "go.micro.bookstore.srv.catalog.CreateCategoryRequest")
	proto.RegisterType((*CreateCategoryResponse)(nil), "go.micro.bookstore.srv.catalog.CreateCategoryResponse")
	proto.RegisterType((*GetCategoryRequest)(nil), "go.micro.bookstore.srv.catalog.GetCategoryRequest")
	proto.RegisterType((*GetCategoryResponse)(nil), "go.micro.bookstore.srv.catalog.GetCategoryResponse")
	proto.RegisterType((*ListCategoryRequest)(nil), "go.micro.bookstore.srv.catalog.ListCategoryRequest")
	proto.RegisterType((*ListCategoryResponse)(nil), "go.micro.bookstore.srv.catalog.ListCategoryResponse")
	proto.RegisterType((*UpdateCategoryRequest)(nil), "go.micro.bookstore.srv.catalog.UpdateCategoryRequest")
	proto.RegisterType((*UpdateCategoryResponse)(nil), "go.micro.bookstore.srv.catalog.UpdateCategoryResponse")
	proto.RegisterType((*DeleteCategoryRequest)(nil), "go.micro.bookstore.srv.catalog.DeleteCategoryRequest")
	proto.RegisterType((*DeleteCategoryResponse)(nil), "go.micro.bookstore.srv.catalog.DeleteCategoryResponse")
	proto.RegisterType((*AddBookRequest)(nil), "go.micro.bookstore.srv.catalog.AddBookRequest")
	proto.RegisterType((*AddBookResponse)(nil), "go.micro.bookstore.srv.catalog.AddBookResponse")
	proto.RegisterType((*GetByBookRequest)(nil), "go.micro.bookstore.srv.catalog.GetByBookRequest")
	proto.RegisterType((*GetByBookResponse)(nil), "go.micro.bookstore.srv.catalog.GetByBookResponse")
	proto.RegisterType((*ListBookRequest)(nil), "go.micro.bookstore.srv.catalog.ListBookRequest")
	proto.RegisterType((*ListBookResponse)(nil), "go.micro.bookstore.srv.catalog.ListBookResponse")
	proto.RegisterType((*RemoveBookRequest)(nil), "go.micro.bookstore.srv.catalog.RemoveBookRequest")
	proto.RegisterType((*RemoveBookResponse)(nil), "go.micro.bookstore.srv.catalog.RemoveBookResponse")
}

func init() { proto.RegisterFile("proto/catalog/catalog.proto", fileDescriptor_0212cf3dccdf82e6) }

var fileDescriptor_0212cf3dccdf82e6 = []byte{
	// 662 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xc4, 0x56, 0xd1, 0x6f, 0xd2, 0x40,
	0x18, 0x5f, 0xc7, 0x36, 0xe0, 0x63, 0x61, 0xdb, 0x6d, 0x20, 0xa9, 0x89, 0xc1, 0x8b, 0x89, 0x24,
	0x86, 0x76, 0x32, 0xf5, 0xc1, 0x27, 0x1d, 0x98, 0xcd, 0xc4, 0x18, 0x43, 0xe2, 0xa3, 0x59, 0x4a,
	0xef, 0xd2, 0x35, 0x03, 0x0e, 0xaf, 0x57, 0x22, 0xf1, 0xc9, 0x07, 0x63, 0x62, 0x7c, 0xf6, 0x4f,
	0xf3, 0xef, 0x31, 0x3d, 0xda, 0xd2, 0x96, 0xce, 0x52, 0xd4, 0xf0, 0x44, 0xef, 0xeb, 0xf7, 0x7d,
	0xbf, 0xdf, 0xf7, 0xbb, 0xeb, 0xef, 0x80, 0xbb, 0x13, 0xce, 0x04, 0xd3, 0x4d, 0x43, 0x18, 0x43,
	0x66, 0x05, 0xbf, 0x9a, 0x8c, 0xa2, 0x7b, 0x16, 0xd3, 0x46, 0xb6, 0xc9, 0x99, 0x36, 0x60, 0xec,
	0xc6, 0x11, 0x8c, 0x53, 0xcd, 0xe1, 0x53, 0xcd, 0xcf, 0x52, 0xdf, 0x59, 0xb6, 0xb8, 0x76, 0x07,
	0x9a, 0xc9, 0x46, 0xba, 0x71, 0x3d, 0x32, 0xc8, 0xd8, 0xe5, 0xae, 0xa3, 0x5b, 0xac, 0x2d, 0xab,
	0xda, 0x61, 0x95, 0x3e, 0xe1, 0x8c, 0xb8, 0xa6, 0xd0, 0x1d, 0x3e, 0xd5, 0xe7, 0x88, 0x41, 0xc4,
	0xff, 0x9d, 0x23, 0x62, 0x0b, 0x4a, 0x5d, 0x43, 0x50, 0x8b, 0xf1, 0x19, 0xaa, 0xc2, 0xb6, 0x4d,
	0x1a, 0x4a, 0x53, 0x69, 0x95, 0xfb, 0xdb, 0x36, 0x41, 0x08, 0x76, 0xc6, 0xc6, 0x88, 0x36, 0xb6,
	0x65, 0x44, 0x3e, 0xa3, 0xfb, 0xb0, 0x4f, 0x6c, 0x67, 0x32, 0x34, 0x66, 0x57, 0xf2, 0x5d, 0x41,
	0xbe, 0xab, 0xf8, 0xb1, 0xb7, 0x5e, 0xca, 0x09, 0xec, 0x4a, 0x1e, 0x8d, 0x9d, 0x66, 0xa1, 0x55,
	0xee, 0xcf, 0x17, 0xf8, 0x03, 0xd4, 0xba, 0x9c, 0x1a, 0x82, 0x06, 0x70, 0x7d, 0xfa, 0xd1, 0xa5,
	0x8e, 0x40, 0x3d, 0x28, 0x99, 0x7e, 0x48, 0x62, 0x57, 0x3a, 0x2d, 0xed, 0xcf, 0x32, 0x68, 0x61,
	0x8b, 0xb0, 0x12, 0x7f, 0x57, 0xa0, 0x9e, 0xec, 0xef, 0x4c, 0xd8, 0xd8, 0xa1, 0xde, 0x18, 0x26,
	0x23, 0x54, 0x36, 0xdf, 0xed, 0xcb, 0x67, 0x54, 0x87, 0x3d, 0x42, 0x85, 0x61, 0x0f, 0xfd, 0xe1,
	0xfc, 0x55, 0x8c, 0x4c, 0x61, 0x6d, 0x32, 0x2d, 0x40, 0x17, 0x54, 0x24, 0x07, 0x0d, 0xe4, 0x54,
	0x16, 0x72, 0xe2, 0x6f, 0x0a, 0x1c, 0xc7, 0x52, 0x37, 0xc6, 0xb9, 0x06, 0xc7, 0x6f, 0x6c, 0x27,
	0x49, 0x1a, 0xff, 0x50, 0xe0, 0x24, 0x1e, 0x5f, 0x83, 0xe1, 0x25, 0x80, 0x8f, 0x63, 0x53, 0xa7,
	0x51, 0x68, 0x16, 0x72, 0x71, 0x8c, 0xd4, 0x7a, 0xa7, 0xe8, 0xfd, 0x84, 0xfc, 0xd7, 0x53, 0x94,
	0xec, 0xbf, 0xb1, 0x1d, 0x79, 0x08, 0xb5, 0x1e, 0x1d, 0xd2, 0xe5, 0x59, 0x13, 0xdf, 0x29, 0xee,
	0x41, 0x3d, 0x99, 0x98, 0x9f, 0x34, 0x7e, 0x05, 0xd5, 0x97, 0x84, 0x9c, 0x33, 0x76, 0x13, 0xe0,
	0xa8, 0x09, 0x4d, 0xcb, 0x0b, 0x72, 0xe8, 0x0e, 0x14, 0xbd, 0x41, 0xae, 0x6c, 0x12, 0xb4, 0xf1,
	0x96, 0xaf, 0x09, 0xe6, 0x70, 0x10, 0xb6, 0x59, 0x43, 0x3a, 0x35, 0x21, 0xdd, 0x2d, 0x98, 0x3b,
	0x31, 0xcc, 0x47, 0x70, 0x78, 0x41, 0xc5, 0xf9, 0x2c, 0x4a, 0x3e, 0x92, 0xac, 0xc4, 0x92, 0xbf,
	0x2a, 0x70, 0x14, 0xc9, 0xde, 0xd8, 0xf6, 0xb6, 0xe1, 0xc0, 0xfb, 0xb0, 0x56, 0x14, 0x1c, 0xff,
	0x54, 0xe0, 0x70, 0x91, 0xff, 0x8f, 0x95, 0x7d, 0x1e, 0xb5, 0xec, 0x4a, 0xe7, 0xc1, 0x6d, 0xe3,
	0x04, 0x77, 0x87, 0x24, 0xe1, 0x1b, 0xfb, 0x25, 0x1c, 0xf5, 0xe9, 0x88, 0x4d, 0xe9, 0x5f, 0x1f,
	0x9d, 0x17, 0x80, 0xa2, 0x9d, 0xf2, 0xcf, 0xd8, 0xf9, 0x55, 0x82, 0x62, 0x77, 0x2e, 0x39, 0xfa,
	0xa2, 0x40, 0x35, 0x7e, 0x23, 0xa0, 0xa7, 0x99, 0xdb, 0x94, 0x76, 0x43, 0xa9, 0xcf, 0xf2, 0x96,
	0xcd, 0x99, 0xe3, 0x2d, 0xf4, 0x09, 0x2a, 0x11, 0x77, 0x47, 0x9d, 0xac, 0x46, 0xcb, 0xb7, 0x86,
	0x7a, 0x96, 0xab, 0x26, 0x44, 0xfe, 0x0c, 0xfb, 0x51, 0xdb, 0x46, 0x99, 0x6d, 0x52, 0xcc, 0x5f,
	0x7d, 0x92, 0xaf, 0x28, 0x04, 0xf7, 0xa4, 0x8f, 0xdb, 0x68, 0xb6, 0xf4, 0xa9, 0xb6, 0x9e, 0x2d,
	0x7d, 0xba, 0x5b, 0xfb, 0x1c, 0xe2, 0xae, 0x98, 0xcd, 0x21, 0xd5, 0x6e, 0xb3, 0x39, 0xa4, 0x9b,
	0x2f, 0xde, 0x42, 0x43, 0x28, 0xfa, 0x5e, 0x88, 0xb4, 0xac, 0x26, 0x71, 0xef, 0x55, 0xf5, 0x95,
	0xf3, 0x43, 0x34, 0x0e, 0xe5, 0xd0, 0xd7, 0xd0, 0xe9, 0x0a, 0xc7, 0x26, 0x66, 0x98, 0xea, 0xe3,
	0x1c, 0x15, 0x21, 0x26, 0x83, 0x52, 0x60, 0x4a, 0x48, 0x5f, 0xe5, 0xb4, 0x44, 0x11, 0x4f, 0x57,
	0x2f, 0x08, 0x01, 0x5d, 0x80, 0x85, 0x47, 0xa0, 0x4c, 0xce, 0x4b, 0xce, 0xa4, 0x76, 0xf2, 0x94,
	0x04, 0xb0, 0x83, 0x3d, 0xf9, 0x6f, 0xf9, 0xec, 0x77, 0x00, 0x00, 0x00, 0xff, 0xff, 0x1e, 0x2b,
	0x2f, 0xc9, 0xbe, 0x0b, 0x00, 0x00,
}
