// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/auth/auth.proto

package go_micro_bookstore_srv_auth

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Token struct {
	AccessToken          string   `protobuf:"bytes,1,opt,name=access_token,json=accessToken,proto3" json:"access_token,omitempty"`
	TokenType            string   `protobuf:"bytes,2,opt,name=token_type,json=tokenType,proto3" json:"token_type,omitempty"`
	ExpiresAt            int64    `protobuf:"varint,3,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Token) Reset()         { *m = Token{} }
func (m *Token) String() string { return proto.CompactTextString(m) }
func (*Token) ProtoMessage()    {}
func (*Token) Descriptor() ([]byte, []int) {
	return fileDescriptor_82b5829f48cfb8e5, []int{0}
}

func (m *Token) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Token.Unmarshal(m, b)
}
func (m *Token) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Token.Marshal(b, m, deterministic)
}
func (m *Token) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Token.Merge(m, src)
}
func (m *Token) XXX_Size() int {
	return xxx_messageInfo_Token.Size(m)
}
func (m *Token) XXX_DiscardUnknown() {
	xxx_messageInfo_Token.DiscardUnknown(m)
}

var xxx_messageInfo_Token proto.InternalMessageInfo

func (m *Token) GetAccessToken() string {
	if m != nil {
		return m.AccessToken
	}
	return ""
}

func (m *Token) GetTokenType() string {
	if m != nil {
		return m.TokenType
	}
	return ""
}

func (m *Token) GetExpiresAt() int64 {
	if m != nil {
		return m.ExpiresAt
	}
	return 0
}

type AuthorizeRequest struct {
	AccessToken          string   `protobuf:"bytes,1,opt,name=access_token,json=accessToken,proto3" json:"access_token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AuthorizeRequest) Reset()         { *m = AuthorizeRequest{} }
func (m *AuthorizeRequest) String() string { return proto.CompactTextString(m) }
func (*AuthorizeRequest) ProtoMessage()    {}
func (*AuthorizeRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_82b5829f48cfb8e5, []int{1}
}

func (m *AuthorizeRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AuthorizeRequest.Unmarshal(m, b)
}
func (m *AuthorizeRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AuthorizeRequest.Marshal(b, m, deterministic)
}
func (m *AuthorizeRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AuthorizeRequest.Merge(m, src)
}
func (m *AuthorizeRequest) XXX_Size() int {
	return xxx_messageInfo_AuthorizeRequest.Size(m)
}
func (m *AuthorizeRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AuthorizeRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AuthorizeRequest proto.InternalMessageInfo

func (m *AuthorizeRequest) GetAccessToken() string {
	if m != nil {
		return m.AccessToken
	}
	return ""
}

type AuthorizeResponse struct {
	Code                 int32    `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Detail               string   `protobuf:"bytes,2,opt,name=detail,proto3" json:"detail,omitempty"`
	ClientId             string   `protobuf:"bytes,3,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AuthorizeResponse) Reset()         { *m = AuthorizeResponse{} }
func (m *AuthorizeResponse) String() string { return proto.CompactTextString(m) }
func (*AuthorizeResponse) ProtoMessage()    {}
func (*AuthorizeResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_82b5829f48cfb8e5, []int{2}
}

func (m *AuthorizeResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AuthorizeResponse.Unmarshal(m, b)
}
func (m *AuthorizeResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AuthorizeResponse.Marshal(b, m, deterministic)
}
func (m *AuthorizeResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AuthorizeResponse.Merge(m, src)
}
func (m *AuthorizeResponse) XXX_Size() int {
	return xxx_messageInfo_AuthorizeResponse.Size(m)
}
func (m *AuthorizeResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AuthorizeResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AuthorizeResponse proto.InternalMessageInfo

func (m *AuthorizeResponse) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *AuthorizeResponse) GetDetail() string {
	if m != nil {
		return m.Detail
	}
	return ""
}

func (m *AuthorizeResponse) GetClientId() string {
	if m != nil {
		return m.ClientId
	}
	return ""
}

type TokenRequest struct {
	ClientId             string   `protobuf:"bytes,1,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	Issuer               string   `protobuf:"bytes,2,opt,name=issuer,proto3" json:"issuer,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TokenRequest) Reset()         { *m = TokenRequest{} }
func (m *TokenRequest) String() string { return proto.CompactTextString(m) }
func (*TokenRequest) ProtoMessage()    {}
func (*TokenRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_82b5829f48cfb8e5, []int{3}
}

func (m *TokenRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TokenRequest.Unmarshal(m, b)
}
func (m *TokenRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TokenRequest.Marshal(b, m, deterministic)
}
func (m *TokenRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TokenRequest.Merge(m, src)
}
func (m *TokenRequest) XXX_Size() int {
	return xxx_messageInfo_TokenRequest.Size(m)
}
func (m *TokenRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_TokenRequest.DiscardUnknown(m)
}

var xxx_messageInfo_TokenRequest proto.InternalMessageInfo

func (m *TokenRequest) GetClientId() string {
	if m != nil {
		return m.ClientId
	}
	return ""
}

func (m *TokenRequest) GetIssuer() string {
	if m != nil {
		return m.Issuer
	}
	return ""
}

type TokenResponse struct {
	Code                 int32    `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Detail               string   `protobuf:"bytes,2,opt,name=detail,proto3" json:"detail,omitempty"`
	Token                *Token   `protobuf:"bytes,3,opt,name=token,proto3" json:"token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TokenResponse) Reset()         { *m = TokenResponse{} }
func (m *TokenResponse) String() string { return proto.CompactTextString(m) }
func (*TokenResponse) ProtoMessage()    {}
func (*TokenResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_82b5829f48cfb8e5, []int{4}
}

func (m *TokenResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TokenResponse.Unmarshal(m, b)
}
func (m *TokenResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TokenResponse.Marshal(b, m, deterministic)
}
func (m *TokenResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TokenResponse.Merge(m, src)
}
func (m *TokenResponse) XXX_Size() int {
	return xxx_messageInfo_TokenResponse.Size(m)
}
func (m *TokenResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_TokenResponse.DiscardUnknown(m)
}

var xxx_messageInfo_TokenResponse proto.InternalMessageInfo

func (m *TokenResponse) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *TokenResponse) GetDetail() string {
	if m != nil {
		return m.Detail
	}
	return ""
}

func (m *TokenResponse) GetToken() *Token {
	if m != nil {
		return m.Token
	}
	return nil
}

type RevokeRequest struct {
	AccessToken          string   `protobuf:"bytes,1,opt,name=access_token,json=accessToken,proto3" json:"access_token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RevokeRequest) Reset()         { *m = RevokeRequest{} }
func (m *RevokeRequest) String() string { return proto.CompactTextString(m) }
func (*RevokeRequest) ProtoMessage()    {}
func (*RevokeRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_82b5829f48cfb8e5, []int{5}
}

func (m *RevokeRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RevokeRequest.Unmarshal(m, b)
}
func (m *RevokeRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RevokeRequest.Marshal(b, m, deterministic)
}
func (m *RevokeRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RevokeRequest.Merge(m, src)
}
func (m *RevokeRequest) XXX_Size() int {
	return xxx_messageInfo_RevokeRequest.Size(m)
}
func (m *RevokeRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RevokeRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RevokeRequest proto.InternalMessageInfo

func (m *RevokeRequest) GetAccessToken() string {
	if m != nil {
		return m.AccessToken
	}
	return ""
}

type RevokeResponse struct {
	Code                 int32    `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Detail               string   `protobuf:"bytes,2,opt,name=detail,proto3" json:"detail,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RevokeResponse) Reset()         { *m = RevokeResponse{} }
func (m *RevokeResponse) String() string { return proto.CompactTextString(m) }
func (*RevokeResponse) ProtoMessage()    {}
func (*RevokeResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_82b5829f48cfb8e5, []int{6}
}

func (m *RevokeResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RevokeResponse.Unmarshal(m, b)
}
func (m *RevokeResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RevokeResponse.Marshal(b, m, deterministic)
}
func (m *RevokeResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RevokeResponse.Merge(m, src)
}
func (m *RevokeResponse) XXX_Size() int {
	return xxx_messageInfo_RevokeResponse.Size(m)
}
func (m *RevokeResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RevokeResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RevokeResponse proto.InternalMessageInfo

func (m *RevokeResponse) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *RevokeResponse) GetDetail() string {
	if m != nil {
		return m.Detail
	}
	return ""
}

func init() {
	proto.RegisterType((*Token)(nil), "go.micro.bookstore.srv.auth.Token")
	proto.RegisterType((*AuthorizeRequest)(nil), "go.micro.bookstore.srv.auth.AuthorizeRequest")
	proto.RegisterType((*AuthorizeResponse)(nil), "go.micro.bookstore.srv.auth.AuthorizeResponse")
	proto.RegisterType((*TokenRequest)(nil), "go.micro.bookstore.srv.auth.TokenRequest")
	proto.RegisterType((*TokenResponse)(nil), "go.micro.bookstore.srv.auth.TokenResponse")
	proto.RegisterType((*RevokeRequest)(nil), "go.micro.bookstore.srv.auth.RevokeRequest")
	proto.RegisterType((*RevokeResponse)(nil), "go.micro.bookstore.srv.auth.RevokeResponse")
}

func init() { proto.RegisterFile("proto/auth/auth.proto", fileDescriptor_82b5829f48cfb8e5) }

var fileDescriptor_82b5829f48cfb8e5 = []byte{
	// 353 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x93, 0x4f, 0x4b, 0xc3, 0x40,
	0x10, 0xc5, 0x4d, 0xff, 0x61, 0xa6, 0xad, 0xe8, 0x82, 0x52, 0x5a, 0x84, 0xba, 0xa7, 0xaa, 0xb8,
	0x42, 0x45, 0xf0, 0xe0, 0xa5, 0x78, 0xf2, 0x1a, 0x7a, 0x14, 0x62, 0x9a, 0x0c, 0x76, 0x69, 0xed,
	0xc6, 0xdd, 0x4d, 0xb1, 0x7e, 0x35, 0xbf, 0x9c, 0xec, 0x6e, 0x52, 0xac, 0x87, 0x90, 0x7a, 0x09,
	0x99, 0xd9, 0xdf, 0xe4, 0xbd, 0xcc, 0x4b, 0xe0, 0x34, 0x95, 0x42, 0x8b, 0xdb, 0x28, 0xd3, 0x73,
	0x7b, 0x61, 0xb6, 0x26, 0x83, 0x37, 0xc1, 0xde, 0x79, 0x2c, 0x05, 0x9b, 0x09, 0xb1, 0x50, 0x5a,
	0x48, 0x64, 0x4a, 0xae, 0x99, 0x41, 0xe8, 0x1c, 0x9a, 0x53, 0xb1, 0xc0, 0x15, 0xb9, 0x80, 0x4e,
	0x14, 0xc7, 0xa8, 0x54, 0xa8, 0x4d, 0xdd, 0xf3, 0x86, 0xde, 0xc8, 0x0f, 0xda, 0xae, 0xe7, 0x90,
	0x73, 0x00, 0x7b, 0x16, 0xea, 0x4d, 0x8a, 0xbd, 0x9a, 0x05, 0x7c, 0xdb, 0x99, 0x6e, 0x52, 0x34,
	0xc7, 0xf8, 0x99, 0x72, 0x89, 0x2a, 0x8c, 0x74, 0xaf, 0x3e, 0xf4, 0x46, 0xf5, 0xc0, 0xcf, 0x3b,
	0x13, 0x4d, 0xef, 0xe1, 0x78, 0x92, 0xe9, 0xb9, 0x90, 0xfc, 0x0b, 0x03, 0xfc, 0xc8, 0x50, 0xe9,
	0x0a, 0xa2, 0xf4, 0x05, 0x4e, 0x7e, 0x8d, 0xa9, 0x54, 0xac, 0x14, 0x12, 0x02, 0x8d, 0x58, 0x24,
	0x68, 0xf9, 0x66, 0x60, 0xef, 0xc9, 0x19, 0xb4, 0x12, 0xd4, 0x11, 0x5f, 0xe6, 0xce, 0xf2, 0x8a,
	0x0c, 0xc0, 0x8f, 0x97, 0x1c, 0x57, 0x3a, 0xe4, 0x89, 0x75, 0xe5, 0x07, 0x87, 0xae, 0xf1, 0x9c,
	0xd0, 0x27, 0xe8, 0x58, 0x99, 0xc2, 0xd0, 0x0e, 0xec, 0xed, 0xc2, 0x46, 0x81, 0x2b, 0x95, 0xa1,
	0x2c, 0x14, 0x5c, 0x45, 0x33, 0xe8, 0xe6, 0x0f, 0xf9, 0x87, 0xbd, 0x07, 0x68, 0xba, 0x77, 0x37,
	0xd6, 0xda, 0x63, 0xca, 0x4a, 0xd2, 0x62, 0x4e, 0xc6, 0x0d, 0xd0, 0x31, 0x74, 0x03, 0x5c, 0x8b,
	0xc5, 0x3e, 0xdb, 0x7c, 0x84, 0xa3, 0x62, 0x66, 0x7f, 0xaf, 0xe3, 0xef, 0x1a, 0x34, 0x4c, 0x18,
	0x64, 0x09, 0xfe, 0x36, 0x14, 0x72, 0x53, 0x6a, 0xf9, 0x6f, 0xe6, 0x7d, 0x56, 0x15, 0x77, 0x06,
	0xe9, 0x01, 0x79, 0x2d, 0xbe, 0xd1, 0xcb, 0x0a, 0xcb, 0xc9, 0x55, 0xae, 0xaa, 0xa0, 0x5b, 0x85,
	0x18, 0x5a, 0x6e, 0x2d, 0xa4, 0x7c, 0x6e, 0x67, 0xdf, 0xfd, 0xeb, 0x4a, 0x6c, 0x21, 0x32, 0x6b,
	0xd9, 0xdf, 0xf1, 0xee, 0x27, 0x00, 0x00, 0xff, 0xff, 0x51, 0xf3, 0x43, 0x14, 0xa7, 0x03, 0x00,
	0x00,
}
