// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/author/author.proto

package go_micro_bookstore_srv_author

import (
	fmt "fmt"
	product "github.com/ahmadnurus/go-micro-bookstore/product/srv/proto/product"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type AuthorProfile struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Username             string   `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	Fullname             string   `protobuf:"bytes,3,opt,name=fullname,proto3" json:"fullname,omitempty"`
	Books                []string `protobuf:"bytes,4,rep,name=books,proto3" json:"books,omitempty"`
	CreatedAt            int64    `protobuf:"varint,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt            int64    `protobuf:"varint,6,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AuthorProfile) Reset()         { *m = AuthorProfile{} }
func (m *AuthorProfile) String() string { return proto.CompactTextString(m) }
func (*AuthorProfile) ProtoMessage()    {}
func (*AuthorProfile) Descriptor() ([]byte, []int) {
	return fileDescriptor_4cc9cb09aef288fa, []int{0}
}

func (m *AuthorProfile) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AuthorProfile.Unmarshal(m, b)
}
func (m *AuthorProfile) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AuthorProfile.Marshal(b, m, deterministic)
}
func (m *AuthorProfile) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AuthorProfile.Merge(m, src)
}
func (m *AuthorProfile) XXX_Size() int {
	return xxx_messageInfo_AuthorProfile.Size(m)
}
func (m *AuthorProfile) XXX_DiscardUnknown() {
	xxx_messageInfo_AuthorProfile.DiscardUnknown(m)
}

var xxx_messageInfo_AuthorProfile proto.InternalMessageInfo

func (m *AuthorProfile) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *AuthorProfile) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *AuthorProfile) GetFullname() string {
	if m != nil {
		return m.Fullname
	}
	return ""
}

func (m *AuthorProfile) GetBooks() []string {
	if m != nil {
		return m.Books
	}
	return nil
}

func (m *AuthorProfile) GetCreatedAt() int64 {
	if m != nil {
		return m.CreatedAt
	}
	return 0
}

func (m *AuthorProfile) GetUpdatedAt() int64 {
	if m != nil {
		return m.UpdatedAt
	}
	return 0
}

type CreateAuthorRequest struct {
	Author               *AuthorProfile `protobuf:"bytes,1,opt,name=author,proto3" json:"author,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *CreateAuthorRequest) Reset()         { *m = CreateAuthorRequest{} }
func (m *CreateAuthorRequest) String() string { return proto.CompactTextString(m) }
func (*CreateAuthorRequest) ProtoMessage()    {}
func (*CreateAuthorRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_4cc9cb09aef288fa, []int{1}
}

func (m *CreateAuthorRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateAuthorRequest.Unmarshal(m, b)
}
func (m *CreateAuthorRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateAuthorRequest.Marshal(b, m, deterministic)
}
func (m *CreateAuthorRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateAuthorRequest.Merge(m, src)
}
func (m *CreateAuthorRequest) XXX_Size() int {
	return xxx_messageInfo_CreateAuthorRequest.Size(m)
}
func (m *CreateAuthorRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateAuthorRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateAuthorRequest proto.InternalMessageInfo

func (m *CreateAuthorRequest) GetAuthor() *AuthorProfile {
	if m != nil {
		return m.Author
	}
	return nil
}

type CreateAuthorResponse struct {
	Code                 int32          `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Detail               string         `protobuf:"bytes,2,opt,name=detail,proto3" json:"detail,omitempty"`
	Author               *AuthorProfile `protobuf:"bytes,3,opt,name=author,proto3" json:"author,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *CreateAuthorResponse) Reset()         { *m = CreateAuthorResponse{} }
func (m *CreateAuthorResponse) String() string { return proto.CompactTextString(m) }
func (*CreateAuthorResponse) ProtoMessage()    {}
func (*CreateAuthorResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_4cc9cb09aef288fa, []int{2}
}

func (m *CreateAuthorResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateAuthorResponse.Unmarshal(m, b)
}
func (m *CreateAuthorResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateAuthorResponse.Marshal(b, m, deterministic)
}
func (m *CreateAuthorResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateAuthorResponse.Merge(m, src)
}
func (m *CreateAuthorResponse) XXX_Size() int {
	return xxx_messageInfo_CreateAuthorResponse.Size(m)
}
func (m *CreateAuthorResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateAuthorResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateAuthorResponse proto.InternalMessageInfo

func (m *CreateAuthorResponse) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *CreateAuthorResponse) GetDetail() string {
	if m != nil {
		return m.Detail
	}
	return ""
}

func (m *CreateAuthorResponse) GetAuthor() *AuthorProfile {
	if m != nil {
		return m.Author
	}
	return nil
}

type GetAuthorRequest struct {
	Username             string   `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetAuthorRequest) Reset()         { *m = GetAuthorRequest{} }
func (m *GetAuthorRequest) String() string { return proto.CompactTextString(m) }
func (*GetAuthorRequest) ProtoMessage()    {}
func (*GetAuthorRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_4cc9cb09aef288fa, []int{3}
}

func (m *GetAuthorRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetAuthorRequest.Unmarshal(m, b)
}
func (m *GetAuthorRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetAuthorRequest.Marshal(b, m, deterministic)
}
func (m *GetAuthorRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetAuthorRequest.Merge(m, src)
}
func (m *GetAuthorRequest) XXX_Size() int {
	return xxx_messageInfo_GetAuthorRequest.Size(m)
}
func (m *GetAuthorRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetAuthorRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetAuthorRequest proto.InternalMessageInfo

func (m *GetAuthorRequest) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

type GetAuthorResponse struct {
	Code                 int32          `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Detail               string         `protobuf:"bytes,2,opt,name=detail,proto3" json:"detail,omitempty"`
	Author               *AuthorProfile `protobuf:"bytes,3,opt,name=author,proto3" json:"author,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *GetAuthorResponse) Reset()         { *m = GetAuthorResponse{} }
func (m *GetAuthorResponse) String() string { return proto.CompactTextString(m) }
func (*GetAuthorResponse) ProtoMessage()    {}
func (*GetAuthorResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_4cc9cb09aef288fa, []int{4}
}

func (m *GetAuthorResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetAuthorResponse.Unmarshal(m, b)
}
func (m *GetAuthorResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetAuthorResponse.Marshal(b, m, deterministic)
}
func (m *GetAuthorResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetAuthorResponse.Merge(m, src)
}
func (m *GetAuthorResponse) XXX_Size() int {
	return xxx_messageInfo_GetAuthorResponse.Size(m)
}
func (m *GetAuthorResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetAuthorResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetAuthorResponse proto.InternalMessageInfo

func (m *GetAuthorResponse) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *GetAuthorResponse) GetDetail() string {
	if m != nil {
		return m.Detail
	}
	return ""
}

func (m *GetAuthorResponse) GetAuthor() *AuthorProfile {
	if m != nil {
		return m.Author
	}
	return nil
}

type GetAuthorByIDRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetAuthorByIDRequest) Reset()         { *m = GetAuthorByIDRequest{} }
func (m *GetAuthorByIDRequest) String() string { return proto.CompactTextString(m) }
func (*GetAuthorByIDRequest) ProtoMessage()    {}
func (*GetAuthorByIDRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_4cc9cb09aef288fa, []int{5}
}

func (m *GetAuthorByIDRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetAuthorByIDRequest.Unmarshal(m, b)
}
func (m *GetAuthorByIDRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetAuthorByIDRequest.Marshal(b, m, deterministic)
}
func (m *GetAuthorByIDRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetAuthorByIDRequest.Merge(m, src)
}
func (m *GetAuthorByIDRequest) XXX_Size() int {
	return xxx_messageInfo_GetAuthorByIDRequest.Size(m)
}
func (m *GetAuthorByIDRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetAuthorByIDRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetAuthorByIDRequest proto.InternalMessageInfo

func (m *GetAuthorByIDRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type GetAuthorByIDResponse struct {
	Code                 int32          `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Detail               string         `protobuf:"bytes,2,opt,name=detail,proto3" json:"detail,omitempty"`
	Author               *AuthorProfile `protobuf:"bytes,3,opt,name=author,proto3" json:"author,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *GetAuthorByIDResponse) Reset()         { *m = GetAuthorByIDResponse{} }
func (m *GetAuthorByIDResponse) String() string { return proto.CompactTextString(m) }
func (*GetAuthorByIDResponse) ProtoMessage()    {}
func (*GetAuthorByIDResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_4cc9cb09aef288fa, []int{6}
}

func (m *GetAuthorByIDResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetAuthorByIDResponse.Unmarshal(m, b)
}
func (m *GetAuthorByIDResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetAuthorByIDResponse.Marshal(b, m, deterministic)
}
func (m *GetAuthorByIDResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetAuthorByIDResponse.Merge(m, src)
}
func (m *GetAuthorByIDResponse) XXX_Size() int {
	return xxx_messageInfo_GetAuthorByIDResponse.Size(m)
}
func (m *GetAuthorByIDResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetAuthorByIDResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetAuthorByIDResponse proto.InternalMessageInfo

func (m *GetAuthorByIDResponse) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *GetAuthorByIDResponse) GetDetail() string {
	if m != nil {
		return m.Detail
	}
	return ""
}

func (m *GetAuthorByIDResponse) GetAuthor() *AuthorProfile {
	if m != nil {
		return m.Author
	}
	return nil
}

type UpdateAuthorRequest struct {
	Author               *AuthorProfile `protobuf:"bytes,1,opt,name=author,proto3" json:"author,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *UpdateAuthorRequest) Reset()         { *m = UpdateAuthorRequest{} }
func (m *UpdateAuthorRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateAuthorRequest) ProtoMessage()    {}
func (*UpdateAuthorRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_4cc9cb09aef288fa, []int{7}
}

func (m *UpdateAuthorRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateAuthorRequest.Unmarshal(m, b)
}
func (m *UpdateAuthorRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateAuthorRequest.Marshal(b, m, deterministic)
}
func (m *UpdateAuthorRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateAuthorRequest.Merge(m, src)
}
func (m *UpdateAuthorRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateAuthorRequest.Size(m)
}
func (m *UpdateAuthorRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateAuthorRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateAuthorRequest proto.InternalMessageInfo

func (m *UpdateAuthorRequest) GetAuthor() *AuthorProfile {
	if m != nil {
		return m.Author
	}
	return nil
}

type UpdateAuthorResponse struct {
	Code                 int32          `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Detail               string         `protobuf:"bytes,2,opt,name=detail,proto3" json:"detail,omitempty"`
	Author               *AuthorProfile `protobuf:"bytes,3,opt,name=author,proto3" json:"author,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *UpdateAuthorResponse) Reset()         { *m = UpdateAuthorResponse{} }
func (m *UpdateAuthorResponse) String() string { return proto.CompactTextString(m) }
func (*UpdateAuthorResponse) ProtoMessage()    {}
func (*UpdateAuthorResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_4cc9cb09aef288fa, []int{8}
}

func (m *UpdateAuthorResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateAuthorResponse.Unmarshal(m, b)
}
func (m *UpdateAuthorResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateAuthorResponse.Marshal(b, m, deterministic)
}
func (m *UpdateAuthorResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateAuthorResponse.Merge(m, src)
}
func (m *UpdateAuthorResponse) XXX_Size() int {
	return xxx_messageInfo_UpdateAuthorResponse.Size(m)
}
func (m *UpdateAuthorResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateAuthorResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateAuthorResponse proto.InternalMessageInfo

func (m *UpdateAuthorResponse) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *UpdateAuthorResponse) GetDetail() string {
	if m != nil {
		return m.Detail
	}
	return ""
}

func (m *UpdateAuthorResponse) GetAuthor() *AuthorProfile {
	if m != nil {
		return m.Author
	}
	return nil
}

type DeleteAuthorRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteAuthorRequest) Reset()         { *m = DeleteAuthorRequest{} }
func (m *DeleteAuthorRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteAuthorRequest) ProtoMessage()    {}
func (*DeleteAuthorRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_4cc9cb09aef288fa, []int{9}
}

func (m *DeleteAuthorRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteAuthorRequest.Unmarshal(m, b)
}
func (m *DeleteAuthorRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteAuthorRequest.Marshal(b, m, deterministic)
}
func (m *DeleteAuthorRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteAuthorRequest.Merge(m, src)
}
func (m *DeleteAuthorRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteAuthorRequest.Size(m)
}
func (m *DeleteAuthorRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteAuthorRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteAuthorRequest proto.InternalMessageInfo

func (m *DeleteAuthorRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type DeleteAuthorResponse struct {
	Code                 int32    `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Detail               string   `protobuf:"bytes,2,opt,name=detail,proto3" json:"detail,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteAuthorResponse) Reset()         { *m = DeleteAuthorResponse{} }
func (m *DeleteAuthorResponse) String() string { return proto.CompactTextString(m) }
func (*DeleteAuthorResponse) ProtoMessage()    {}
func (*DeleteAuthorResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_4cc9cb09aef288fa, []int{10}
}

func (m *DeleteAuthorResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteAuthorResponse.Unmarshal(m, b)
}
func (m *DeleteAuthorResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteAuthorResponse.Marshal(b, m, deterministic)
}
func (m *DeleteAuthorResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteAuthorResponse.Merge(m, src)
}
func (m *DeleteAuthorResponse) XXX_Size() int {
	return xxx_messageInfo_DeleteAuthorResponse.Size(m)
}
func (m *DeleteAuthorResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteAuthorResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteAuthorResponse proto.InternalMessageInfo

func (m *DeleteAuthorResponse) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *DeleteAuthorResponse) GetDetail() string {
	if m != nil {
		return m.Detail
	}
	return ""
}

type AddAuthorBookRequest struct {
	Author               string   `protobuf:"bytes,1,opt,name=author,proto3" json:"author,omitempty"`
	BookId               string   `protobuf:"bytes,2,opt,name=book_id,json=bookId,proto3" json:"book_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddAuthorBookRequest) Reset()         { *m = AddAuthorBookRequest{} }
func (m *AddAuthorBookRequest) String() string { return proto.CompactTextString(m) }
func (*AddAuthorBookRequest) ProtoMessage()    {}
func (*AddAuthorBookRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_4cc9cb09aef288fa, []int{11}
}

func (m *AddAuthorBookRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddAuthorBookRequest.Unmarshal(m, b)
}
func (m *AddAuthorBookRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddAuthorBookRequest.Marshal(b, m, deterministic)
}
func (m *AddAuthorBookRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddAuthorBookRequest.Merge(m, src)
}
func (m *AddAuthorBookRequest) XXX_Size() int {
	return xxx_messageInfo_AddAuthorBookRequest.Size(m)
}
func (m *AddAuthorBookRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AddAuthorBookRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AddAuthorBookRequest proto.InternalMessageInfo

func (m *AddAuthorBookRequest) GetAuthor() string {
	if m != nil {
		return m.Author
	}
	return ""
}

func (m *AddAuthorBookRequest) GetBookId() string {
	if m != nil {
		return m.BookId
	}
	return ""
}

type AddAuthorBookResponse struct {
	Code                 int32    `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Detail               string   `protobuf:"bytes,2,opt,name=detail,proto3" json:"detail,omitempty"`
	Author               string   `protobuf:"bytes,3,opt,name=author,proto3" json:"author,omitempty"`
	BookId               string   `protobuf:"bytes,4,opt,name=book_id,json=bookId,proto3" json:"book_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddAuthorBookResponse) Reset()         { *m = AddAuthorBookResponse{} }
func (m *AddAuthorBookResponse) String() string { return proto.CompactTextString(m) }
func (*AddAuthorBookResponse) ProtoMessage()    {}
func (*AddAuthorBookResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_4cc9cb09aef288fa, []int{12}
}

func (m *AddAuthorBookResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddAuthorBookResponse.Unmarshal(m, b)
}
func (m *AddAuthorBookResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddAuthorBookResponse.Marshal(b, m, deterministic)
}
func (m *AddAuthorBookResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddAuthorBookResponse.Merge(m, src)
}
func (m *AddAuthorBookResponse) XXX_Size() int {
	return xxx_messageInfo_AddAuthorBookResponse.Size(m)
}
func (m *AddAuthorBookResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AddAuthorBookResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AddAuthorBookResponse proto.InternalMessageInfo

func (m *AddAuthorBookResponse) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *AddAuthorBookResponse) GetDetail() string {
	if m != nil {
		return m.Detail
	}
	return ""
}

func (m *AddAuthorBookResponse) GetAuthor() string {
	if m != nil {
		return m.Author
	}
	return ""
}

func (m *AddAuthorBookResponse) GetBookId() string {
	if m != nil {
		return m.BookId
	}
	return ""
}

type GetAuthorBookRequest struct {
	Author               string   `protobuf:"bytes,1,opt,name=author,proto3" json:"author,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetAuthorBookRequest) Reset()         { *m = GetAuthorBookRequest{} }
func (m *GetAuthorBookRequest) String() string { return proto.CompactTextString(m) }
func (*GetAuthorBookRequest) ProtoMessage()    {}
func (*GetAuthorBookRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_4cc9cb09aef288fa, []int{13}
}

func (m *GetAuthorBookRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetAuthorBookRequest.Unmarshal(m, b)
}
func (m *GetAuthorBookRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetAuthorBookRequest.Marshal(b, m, deterministic)
}
func (m *GetAuthorBookRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetAuthorBookRequest.Merge(m, src)
}
func (m *GetAuthorBookRequest) XXX_Size() int {
	return xxx_messageInfo_GetAuthorBookRequest.Size(m)
}
func (m *GetAuthorBookRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetAuthorBookRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetAuthorBookRequest proto.InternalMessageInfo

func (m *GetAuthorBookRequest) GetAuthor() string {
	if m != nil {
		return m.Author
	}
	return ""
}

type GetAuthorBookResponse struct {
	Code                 int32           `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Detail               string          `protobuf:"bytes,2,opt,name=detail,proto3" json:"detail,omitempty"`
	Author               string          `protobuf:"bytes,3,opt,name=author,proto3" json:"author,omitempty"`
	Books                []*product.Book `protobuf:"bytes,4,rep,name=books,proto3" json:"books,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *GetAuthorBookResponse) Reset()         { *m = GetAuthorBookResponse{} }
func (m *GetAuthorBookResponse) String() string { return proto.CompactTextString(m) }
func (*GetAuthorBookResponse) ProtoMessage()    {}
func (*GetAuthorBookResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_4cc9cb09aef288fa, []int{14}
}

func (m *GetAuthorBookResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetAuthorBookResponse.Unmarshal(m, b)
}
func (m *GetAuthorBookResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetAuthorBookResponse.Marshal(b, m, deterministic)
}
func (m *GetAuthorBookResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetAuthorBookResponse.Merge(m, src)
}
func (m *GetAuthorBookResponse) XXX_Size() int {
	return xxx_messageInfo_GetAuthorBookResponse.Size(m)
}
func (m *GetAuthorBookResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetAuthorBookResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetAuthorBookResponse proto.InternalMessageInfo

func (m *GetAuthorBookResponse) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *GetAuthorBookResponse) GetDetail() string {
	if m != nil {
		return m.Detail
	}
	return ""
}

func (m *GetAuthorBookResponse) GetAuthor() string {
	if m != nil {
		return m.Author
	}
	return ""
}

func (m *GetAuthorBookResponse) GetBooks() []*product.Book {
	if m != nil {
		return m.Books
	}
	return nil
}

type RemoveAuthorBookRequest struct {
	Author               string   `protobuf:"bytes,1,opt,name=author,proto3" json:"author,omitempty"`
	BookId               string   `protobuf:"bytes,2,opt,name=book_id,json=bookId,proto3" json:"book_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RemoveAuthorBookRequest) Reset()         { *m = RemoveAuthorBookRequest{} }
func (m *RemoveAuthorBookRequest) String() string { return proto.CompactTextString(m) }
func (*RemoveAuthorBookRequest) ProtoMessage()    {}
func (*RemoveAuthorBookRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_4cc9cb09aef288fa, []int{15}
}

func (m *RemoveAuthorBookRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RemoveAuthorBookRequest.Unmarshal(m, b)
}
func (m *RemoveAuthorBookRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RemoveAuthorBookRequest.Marshal(b, m, deterministic)
}
func (m *RemoveAuthorBookRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RemoveAuthorBookRequest.Merge(m, src)
}
func (m *RemoveAuthorBookRequest) XXX_Size() int {
	return xxx_messageInfo_RemoveAuthorBookRequest.Size(m)
}
func (m *RemoveAuthorBookRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RemoveAuthorBookRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RemoveAuthorBookRequest proto.InternalMessageInfo

func (m *RemoveAuthorBookRequest) GetAuthor() string {
	if m != nil {
		return m.Author
	}
	return ""
}

func (m *RemoveAuthorBookRequest) GetBookId() string {
	if m != nil {
		return m.BookId
	}
	return ""
}

type RemoveAuthorBookResponse struct {
	Code                 int32    `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Detail               string   `protobuf:"bytes,2,opt,name=detail,proto3" json:"detail,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RemoveAuthorBookResponse) Reset()         { *m = RemoveAuthorBookResponse{} }
func (m *RemoveAuthorBookResponse) String() string { return proto.CompactTextString(m) }
func (*RemoveAuthorBookResponse) ProtoMessage()    {}
func (*RemoveAuthorBookResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_4cc9cb09aef288fa, []int{16}
}

func (m *RemoveAuthorBookResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RemoveAuthorBookResponse.Unmarshal(m, b)
}
func (m *RemoveAuthorBookResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RemoveAuthorBookResponse.Marshal(b, m, deterministic)
}
func (m *RemoveAuthorBookResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RemoveAuthorBookResponse.Merge(m, src)
}
func (m *RemoveAuthorBookResponse) XXX_Size() int {
	return xxx_messageInfo_RemoveAuthorBookResponse.Size(m)
}
func (m *RemoveAuthorBookResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RemoveAuthorBookResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RemoveAuthorBookResponse proto.InternalMessageInfo

func (m *RemoveAuthorBookResponse) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *RemoveAuthorBookResponse) GetDetail() string {
	if m != nil {
		return m.Detail
	}
	return ""
}

func init() {
	proto.RegisterType((*AuthorProfile)(nil), "go.micro.bookstore.srv.author.AuthorProfile")
	proto.RegisterType((*CreateAuthorRequest)(nil), "go.micro.bookstore.srv.author.CreateAuthorRequest")
	proto.RegisterType((*CreateAuthorResponse)(nil), "go.micro.bookstore.srv.author.CreateAuthorResponse")
	proto.RegisterType((*GetAuthorRequest)(nil), "go.micro.bookstore.srv.author.GetAuthorRequest")
	proto.RegisterType((*GetAuthorResponse)(nil), "go.micro.bookstore.srv.author.GetAuthorResponse")
	proto.RegisterType((*GetAuthorByIDRequest)(nil), "go.micro.bookstore.srv.author.GetAuthorByIDRequest")
	proto.RegisterType((*GetAuthorByIDResponse)(nil), "go.micro.bookstore.srv.author.GetAuthorByIDResponse")
	proto.RegisterType((*UpdateAuthorRequest)(nil), "go.micro.bookstore.srv.author.UpdateAuthorRequest")
	proto.RegisterType((*UpdateAuthorResponse)(nil), "go.micro.bookstore.srv.author.UpdateAuthorResponse")
	proto.RegisterType((*DeleteAuthorRequest)(nil), "go.micro.bookstore.srv.author.DeleteAuthorRequest")
	proto.RegisterType((*DeleteAuthorResponse)(nil), "go.micro.bookstore.srv.author.DeleteAuthorResponse")
	proto.RegisterType((*AddAuthorBookRequest)(nil), "go.micro.bookstore.srv.author.AddAuthorBookRequest")
	proto.RegisterType((*AddAuthorBookResponse)(nil), "go.micro.bookstore.srv.author.AddAuthorBookResponse")
	proto.RegisterType((*GetAuthorBookRequest)(nil), "go.micro.bookstore.srv.author.GetAuthorBookRequest")
	proto.RegisterType((*GetAuthorBookResponse)(nil), "go.micro.bookstore.srv.author.GetAuthorBookResponse")
	proto.RegisterType((*RemoveAuthorBookRequest)(nil), "go.micro.bookstore.srv.author.RemoveAuthorBookRequest")
	proto.RegisterType((*RemoveAuthorBookResponse)(nil), "go.micro.bookstore.srv.author.RemoveAuthorBookResponse")
}

func init() { proto.RegisterFile("proto/author/author.proto", fileDescriptor_4cc9cb09aef288fa) }

var fileDescriptor_4cc9cb09aef288fa = []byte{
	// 632 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xc4, 0x56, 0xcd, 0x6e, 0xd3, 0x40,
	0x10, 0xc6, 0xf9, 0x2b, 0x99, 0xb6, 0xa8, 0x6c, 0xd2, 0x34, 0x58, 0xaa, 0x14, 0x59, 0x80, 0x72,
	0xa0, 0x36, 0x4a, 0x10, 0x48, 0xdc, 0x52, 0x22, 0xaa, 0x72, 0xaa, 0x2c, 0x71, 0xea, 0xa1, 0x72,
	0xb2, 0xdb, 0xc4, 0x6a, 0x92, 0x35, 0xeb, 0x75, 0xa4, 0x48, 0x5c, 0x2b, 0xc1, 0x13, 0xf0, 0x10,
	0x3c, 0x1b, 0xef, 0x80, 0xb2, 0x6b, 0x5b, 0x5e, 0xe3, 0xe2, 0x18, 0x5a, 0xe5, 0xe4, 0xee, 0xce,
	0xce, 0x7c, 0xdf, 0x7c, 0x33, 0xfd, 0x14, 0x78, 0xe6, 0x31, 0xca, 0xa9, 0xe5, 0x04, 0x7c, 0x4a,
	0x59, 0xf8, 0x31, 0xc5, 0x1d, 0x3a, 0x9e, 0x50, 0x73, 0xee, 0x8e, 0x19, 0x35, 0x47, 0x94, 0xde,
	0xf8, 0x9c, 0x32, 0x62, 0xfa, 0x6c, 0x69, 0xca, 0x47, 0xfa, 0xc5, 0xc4, 0xe5, 0xd3, 0x60, 0x64,
	0x8e, 0xe9, 0xdc, 0x72, 0xa6, 0x73, 0x07, 0x2f, 0x02, 0x16, 0xf8, 0xd6, 0x84, 0x9e, 0x88, 0xa4,
	0x93, 0x38, 0xc9, 0xf2, 0x18, 0xc5, 0xc1, 0x98, 0x5b, 0x3e, 0x5b, 0x5a, 0x12, 0x2e, 0xba, 0x09,
	0xbf, 0x12, 0xd0, 0xf8, 0xa9, 0xc1, 0xfe, 0x40, 0x14, 0xbf, 0x60, 0xf4, 0xda, 0x9d, 0x11, 0xf4,
	0x04, 0x4a, 0x2e, 0x6e, 0x6b, 0x1d, 0xad, 0x5b, 0xb7, 0x4b, 0x2e, 0x46, 0x3a, 0x3c, 0x0e, 0x7c,
	0xc2, 0x16, 0xce, 0x9c, 0xb4, 0x4b, 0xe2, 0x36, 0x3e, 0xaf, 0x63, 0xd7, 0xc1, 0x6c, 0x26, 0x62,
	0x65, 0x19, 0x8b, 0xce, 0xa8, 0x09, 0x55, 0x41, 0xa7, 0x5d, 0xe9, 0x94, 0xbb, 0x75, 0x5b, 0x1e,
	0xd0, 0x31, 0xc0, 0x98, 0x11, 0x87, 0x13, 0x7c, 0xe5, 0xf0, 0x76, 0xb5, 0xa3, 0x75, 0xcb, 0x76,
	0x3d, 0xbc, 0x19, 0xf0, 0x75, 0x38, 0xf0, 0x70, 0x14, 0xae, 0xc9, 0x70, 0x78, 0x33, 0xe0, 0xc6,
	0x25, 0x34, 0x3e, 0x88, 0xb7, 0x92, 0xb2, 0x4d, 0xbe, 0x04, 0xc4, 0xe7, 0x68, 0x08, 0x35, 0x29,
	0x90, 0xa0, 0xbd, 0xdb, 0x7b, 0x65, 0xfe, 0x55, 0x46, 0x53, 0x69, 0xd8, 0x0e, 0x73, 0x8d, 0x6f,
	0x1a, 0x34, 0xd5, 0xea, 0xbe, 0x47, 0x17, 0x3e, 0x41, 0x08, 0x2a, 0x63, 0x8a, 0x89, 0x28, 0x5e,
	0xb5, 0xc5, 0xdf, 0xa8, 0x05, 0x35, 0x4c, 0xb8, 0xe3, 0xce, 0x42, 0x4d, 0xc2, 0x53, 0x82, 0x4a,
	0xf9, 0x3f, 0xa8, 0x98, 0x70, 0x70, 0x46, 0xb8, 0xda, 0x64, 0x72, 0x0e, 0x9a, 0x3a, 0x07, 0xe3,
	0x56, 0x83, 0xa7, 0x89, 0x84, 0xad, 0xf1, 0x7e, 0x09, 0xcd, 0x98, 0xc6, 0xe9, 0xea, 0x7c, 0x18,
	0x71, 0x4f, 0xed, 0x94, 0xf1, 0x5d, 0x83, 0xc3, 0xd4, 0xc3, 0xad, 0x71, 0xbe, 0x84, 0xc6, 0x67,
	0xb1, 0x60, 0x0f, 0xb5, 0x53, 0x6a, 0xf5, 0xad, 0xf5, 0xf9, 0x02, 0x1a, 0x43, 0x32, 0x23, 0xe9,
	0x3e, 0xd3, 0xa3, 0x39, 0x85, 0xa6, 0xfa, 0xac, 0x38, 0x61, 0xe3, 0x0c, 0x9a, 0x03, 0x8c, 0xc3,
	0xe9, 0x52, 0x7a, 0x13, 0x61, 0xb5, 0x14, 0x4d, 0xeb, 0x11, 0x35, 0x74, 0x04, 0x3b, 0xeb, 0x46,
	0xae, 0x5c, 0x1c, 0x15, 0x5a, 0x1f, 0xcf, 0xb1, 0xc1, 0xe1, 0x30, 0x55, 0xe8, 0x1f, 0xe4, 0x6b,
	0x29, 0xf2, 0x65, 0xa2, 0x56, 0x14, 0x54, 0x33, 0xb9, 0xc5, 0xf9, 0xf4, 0x8d, 0x1f, 0xca, 0x36,
	0xdf, 0x37, 0xcd, 0xf7, 0x49, 0x1f, 0xdd, 0xed, 0x3d, 0xbf, 0x6b, 0xf8, 0x91, 0xaf, 0x0b, 0x02,
	0x32, 0xc5, 0xf8, 0x04, 0x47, 0x36, 0x99, 0xd3, 0x25, 0xb9, 0x87, 0x59, 0x7c, 0x84, 0xf6, 0x9f,
	0xb5, 0x8a, 0xf7, 0xd9, 0xfb, 0xb5, 0x03, 0x35, 0x59, 0x02, 0xad, 0x60, 0x2f, 0x69, 0xb8, 0xa8,
	0x97, 0xb3, 0xd8, 0x19, 0xde, 0xaf, 0xf7, 0x0b, 0xe5, 0x48, 0xbe, 0xc6, 0x23, 0xe4, 0x41, 0x3d,
	0x1e, 0x19, 0xb2, 0x72, 0x6a, 0xa4, 0xbd, 0x58, 0x7f, 0xbd, 0x79, 0x42, 0x8c, 0xf8, 0x15, 0xf6,
	0x15, 0xcb, 0x43, 0xfd, 0x4d, 0x8b, 0x24, 0x9c, 0x54, 0x7f, 0x53, 0x2c, 0x29, 0x46, 0x5f, 0xc1,
	0x5e, 0xd2, 0x87, 0x72, 0xa5, 0xce, 0xb0, 0xc4, 0x5c, 0xa9, 0xb3, 0x8c, 0x4e, 0x42, 0x27, 0x1d,
	0x25, 0x17, 0x3a, 0xc3, 0xa5, 0x72, 0xa1, 0xb3, 0x2c, 0x4b, 0x6a, 0xae, 0xf8, 0x47, 0xae, 0xe6,
	0x59, 0xb6, 0x95, 0xab, 0x79, 0xa6, 0x45, 0xa5, 0x27, 0xbe, 0x09, 0x7a, 0x96, 0xeb, 0x14, 0x98,
	0xb8, 0x8a, 0x7e, 0xab, 0xc1, 0x41, 0xfa, 0x1f, 0x16, 0xbd, 0xcd, 0x29, 0x76, 0x87, 0x5b, 0xe8,
	0xef, 0x0a, 0xe7, 0x45, 0x3c, 0x46, 0x35, 0xf1, 0x43, 0xb3, 0xff, 0x3b, 0x00, 0x00, 0xff, 0xff,
	0x62, 0x17, 0xff, 0xdd, 0xf6, 0x0a, 0x00, 0x00,
}
