// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/verification/verification.proto

package go_micro_bookstore_srv_verification

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type VerifyAccountRequest struct {
	AccountId            string   `protobuf:"bytes,1,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	Token                string   `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *VerifyAccountRequest) Reset()         { *m = VerifyAccountRequest{} }
func (m *VerifyAccountRequest) String() string { return proto.CompactTextString(m) }
func (*VerifyAccountRequest) ProtoMessage()    {}
func (*VerifyAccountRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_4081558d943294a1, []int{0}
}

func (m *VerifyAccountRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VerifyAccountRequest.Unmarshal(m, b)
}
func (m *VerifyAccountRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VerifyAccountRequest.Marshal(b, m, deterministic)
}
func (m *VerifyAccountRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VerifyAccountRequest.Merge(m, src)
}
func (m *VerifyAccountRequest) XXX_Size() int {
	return xxx_messageInfo_VerifyAccountRequest.Size(m)
}
func (m *VerifyAccountRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_VerifyAccountRequest.DiscardUnknown(m)
}

var xxx_messageInfo_VerifyAccountRequest proto.InternalMessageInfo

func (m *VerifyAccountRequest) GetAccountId() string {
	if m != nil {
		return m.AccountId
	}
	return ""
}

func (m *VerifyAccountRequest) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

type VerifyAccountResponse struct {
	Code                 int32    `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Detail               string   `protobuf:"bytes,2,opt,name=detail,proto3" json:"detail,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *VerifyAccountResponse) Reset()         { *m = VerifyAccountResponse{} }
func (m *VerifyAccountResponse) String() string { return proto.CompactTextString(m) }
func (*VerifyAccountResponse) ProtoMessage()    {}
func (*VerifyAccountResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_4081558d943294a1, []int{1}
}

func (m *VerifyAccountResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VerifyAccountResponse.Unmarshal(m, b)
}
func (m *VerifyAccountResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VerifyAccountResponse.Marshal(b, m, deterministic)
}
func (m *VerifyAccountResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VerifyAccountResponse.Merge(m, src)
}
func (m *VerifyAccountResponse) XXX_Size() int {
	return xxx_messageInfo_VerifyAccountResponse.Size(m)
}
func (m *VerifyAccountResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_VerifyAccountResponse.DiscardUnknown(m)
}

var xxx_messageInfo_VerifyAccountResponse proto.InternalMessageInfo

func (m *VerifyAccountResponse) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *VerifyAccountResponse) GetDetail() string {
	if m != nil {
		return m.Detail
	}
	return ""
}

func init() {
	proto.RegisterType((*VerifyAccountRequest)(nil), "go.micro.bookstore.srv.verification.VerifyAccountRequest")
	proto.RegisterType((*VerifyAccountResponse)(nil), "go.micro.bookstore.srv.verification.VerifyAccountResponse")
}

func init() {
	proto.RegisterFile("proto/verification/verification.proto", fileDescriptor_4081558d943294a1)
}

var fileDescriptor_4081558d943294a1 = []byte{
	// 213 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x52, 0x2d, 0x28, 0xca, 0x2f,
	0xc9, 0xd7, 0x2f, 0x4b, 0x2d, 0xca, 0x4c, 0xcb, 0x4c, 0x4e, 0x2c, 0xc9, 0xcc, 0xcf, 0x43, 0xe1,
	0xe8, 0x81, 0xe5, 0x85, 0x94, 0xd3, 0xf3, 0xf5, 0x72, 0x33, 0x93, 0x8b, 0xf2, 0xf5, 0x92, 0xf2,
	0xf3, 0xb3, 0x8b, 0x4b, 0xf2, 0x8b, 0x52, 0xf5, 0x8a, 0x8b, 0xca, 0xf4, 0x90, 0x95, 0x2a, 0x79,
	0x73, 0x89, 0x84, 0x81, 0xf8, 0x95, 0x8e, 0xc9, 0xc9, 0xf9, 0xa5, 0x79, 0x25, 0x41, 0xa9, 0x85,
	0xa5, 0xa9, 0xc5, 0x25, 0x42, 0xb2, 0x5c, 0x5c, 0x89, 0x10, 0x91, 0xf8, 0xcc, 0x14, 0x09, 0x46,
	0x05, 0x46, 0x0d, 0xce, 0x20, 0x4e, 0xa8, 0x88, 0x67, 0x8a, 0x90, 0x08, 0x17, 0x6b, 0x49, 0x7e,
	0x76, 0x6a, 0x9e, 0x04, 0x13, 0x58, 0x06, 0xc2, 0x51, 0x72, 0xe6, 0x12, 0x45, 0x33, 0xac, 0xb8,
	0x20, 0x3f, 0xaf, 0x38, 0x55, 0x48, 0x88, 0x8b, 0x25, 0x39, 0x3f, 0x25, 0x15, 0x6c, 0x0e, 0x6b,
	0x10, 0x98, 0x2d, 0x24, 0xc6, 0xc5, 0x96, 0x92, 0x5a, 0x92, 0x98, 0x99, 0x03, 0x35, 0x03, 0xca,
	0x33, 0x9a, 0xc9, 0xc8, 0xc5, 0x13, 0x86, 0xe4, 0x44, 0xa1, 0x0e, 0x46, 0x2e, 0x5e, 0x14, 0x63,
	0x85, 0x2c, 0xf5, 0x88, 0xf0, 0x9a, 0x1e, 0x36, 0x7f, 0x49, 0x59, 0x91, 0xa3, 0x15, 0xe2, 0x0b,
	0x25, 0x86, 0x24, 0x36, 0x70, 0xc8, 0x1a, 0x03, 0x02, 0x00, 0x00, 0xff, 0xff, 0xb5, 0xc0, 0x6e,
	0x56, 0x82, 0x01, 0x00, 0x00,
}
