// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/account/account.proto

package go_micro_bookstore_srv_account

import (
	fmt "fmt"
	auth "github.com/ahmadnurus/go-micro-bookstore/auth/srv/proto/auth"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Credential struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Username             string   `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	Email                string   `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	Password             string   `protobuf:"bytes,4,opt,name=password,proto3" json:"password,omitempty"`
	ProfileId            string   `protobuf:"bytes,5,opt,name=profile_id,json=profileId,proto3" json:"profile_id,omitempty"`
	AuthorId             string   `protobuf:"bytes,6,opt,name=author_id,json=authorId,proto3" json:"author_id,omitempty"`
	IsVerified           bool     `protobuf:"varint,7,opt,name=is_verified,json=isVerified,proto3" json:"is_verified,omitempty"`
	LastLogin            int64    `protobuf:"varint,8,opt,name=last_login,json=lastLogin,proto3" json:"last_login,omitempty"`
	CreatedAt            int64    `protobuf:"varint,9,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt            int64    `protobuf:"varint,10,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Credential) Reset()         { *m = Credential{} }
func (m *Credential) String() string { return proto.CompactTextString(m) }
func (*Credential) ProtoMessage()    {}
func (*Credential) Descriptor() ([]byte, []int) {
	return fileDescriptor_5d492a0187472a3b, []int{0}
}

func (m *Credential) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Credential.Unmarshal(m, b)
}
func (m *Credential) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Credential.Marshal(b, m, deterministic)
}
func (m *Credential) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Credential.Merge(m, src)
}
func (m *Credential) XXX_Size() int {
	return xxx_messageInfo_Credential.Size(m)
}
func (m *Credential) XXX_DiscardUnknown() {
	xxx_messageInfo_Credential.DiscardUnknown(m)
}

var xxx_messageInfo_Credential proto.InternalMessageInfo

func (m *Credential) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Credential) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *Credential) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *Credential) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *Credential) GetProfileId() string {
	if m != nil {
		return m.ProfileId
	}
	return ""
}

func (m *Credential) GetAuthorId() string {
	if m != nil {
		return m.AuthorId
	}
	return ""
}

func (m *Credential) GetIsVerified() bool {
	if m != nil {
		return m.IsVerified
	}
	return false
}

func (m *Credential) GetLastLogin() int64 {
	if m != nil {
		return m.LastLogin
	}
	return 0
}

func (m *Credential) GetCreatedAt() int64 {
	if m != nil {
		return m.CreatedAt
	}
	return 0
}

func (m *Credential) GetUpdatedAt() int64 {
	if m != nil {
		return m.UpdatedAt
	}
	return 0
}

type CreateAccountRequest struct {
	Account              *Credential `protobuf:"bytes,1,opt,name=account,proto3" json:"account,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *CreateAccountRequest) Reset()         { *m = CreateAccountRequest{} }
func (m *CreateAccountRequest) String() string { return proto.CompactTextString(m) }
func (*CreateAccountRequest) ProtoMessage()    {}
func (*CreateAccountRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_5d492a0187472a3b, []int{1}
}

func (m *CreateAccountRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateAccountRequest.Unmarshal(m, b)
}
func (m *CreateAccountRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateAccountRequest.Marshal(b, m, deterministic)
}
func (m *CreateAccountRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateAccountRequest.Merge(m, src)
}
func (m *CreateAccountRequest) XXX_Size() int {
	return xxx_messageInfo_CreateAccountRequest.Size(m)
}
func (m *CreateAccountRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateAccountRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateAccountRequest proto.InternalMessageInfo

func (m *CreateAccountRequest) GetAccount() *Credential {
	if m != nil {
		return m.Account
	}
	return nil
}

type CreateAccountResponse struct {
	Code                 int32       `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Detail               string      `protobuf:"bytes,2,opt,name=detail,proto3" json:"detail,omitempty"`
	Account              *Credential `protobuf:"bytes,3,opt,name=account,proto3" json:"account,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *CreateAccountResponse) Reset()         { *m = CreateAccountResponse{} }
func (m *CreateAccountResponse) String() string { return proto.CompactTextString(m) }
func (*CreateAccountResponse) ProtoMessage()    {}
func (*CreateAccountResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_5d492a0187472a3b, []int{2}
}

func (m *CreateAccountResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateAccountResponse.Unmarshal(m, b)
}
func (m *CreateAccountResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateAccountResponse.Marshal(b, m, deterministic)
}
func (m *CreateAccountResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateAccountResponse.Merge(m, src)
}
func (m *CreateAccountResponse) XXX_Size() int {
	return xxx_messageInfo_CreateAccountResponse.Size(m)
}
func (m *CreateAccountResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateAccountResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateAccountResponse proto.InternalMessageInfo

func (m *CreateAccountResponse) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *CreateAccountResponse) GetDetail() string {
	if m != nil {
		return m.Detail
	}
	return ""
}

func (m *CreateAccountResponse) GetAccount() *Credential {
	if m != nil {
		return m.Account
	}
	return nil
}

type GetAccountRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetAccountRequest) Reset()         { *m = GetAccountRequest{} }
func (m *GetAccountRequest) String() string { return proto.CompactTextString(m) }
func (*GetAccountRequest) ProtoMessage()    {}
func (*GetAccountRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_5d492a0187472a3b, []int{3}
}

func (m *GetAccountRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetAccountRequest.Unmarshal(m, b)
}
func (m *GetAccountRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetAccountRequest.Marshal(b, m, deterministic)
}
func (m *GetAccountRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetAccountRequest.Merge(m, src)
}
func (m *GetAccountRequest) XXX_Size() int {
	return xxx_messageInfo_GetAccountRequest.Size(m)
}
func (m *GetAccountRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetAccountRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetAccountRequest proto.InternalMessageInfo

func (m *GetAccountRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type GetAccountResponse struct {
	Code                 int32       `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Detail               string      `protobuf:"bytes,2,opt,name=detail,proto3" json:"detail,omitempty"`
	Account              *Credential `protobuf:"bytes,3,opt,name=account,proto3" json:"account,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *GetAccountResponse) Reset()         { *m = GetAccountResponse{} }
func (m *GetAccountResponse) String() string { return proto.CompactTextString(m) }
func (*GetAccountResponse) ProtoMessage()    {}
func (*GetAccountResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_5d492a0187472a3b, []int{4}
}

func (m *GetAccountResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetAccountResponse.Unmarshal(m, b)
}
func (m *GetAccountResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetAccountResponse.Marshal(b, m, deterministic)
}
func (m *GetAccountResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetAccountResponse.Merge(m, src)
}
func (m *GetAccountResponse) XXX_Size() int {
	return xxx_messageInfo_GetAccountResponse.Size(m)
}
func (m *GetAccountResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetAccountResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetAccountResponse proto.InternalMessageInfo

func (m *GetAccountResponse) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *GetAccountResponse) GetDetail() string {
	if m != nil {
		return m.Detail
	}
	return ""
}

func (m *GetAccountResponse) GetAccount() *Credential {
	if m != nil {
		return m.Account
	}
	return nil
}

type UpdateAccountRequest struct {
	Account              *Credential `protobuf:"bytes,1,opt,name=account,proto3" json:"account,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *UpdateAccountRequest) Reset()         { *m = UpdateAccountRequest{} }
func (m *UpdateAccountRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateAccountRequest) ProtoMessage()    {}
func (*UpdateAccountRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_5d492a0187472a3b, []int{5}
}

func (m *UpdateAccountRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateAccountRequest.Unmarshal(m, b)
}
func (m *UpdateAccountRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateAccountRequest.Marshal(b, m, deterministic)
}
func (m *UpdateAccountRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateAccountRequest.Merge(m, src)
}
func (m *UpdateAccountRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateAccountRequest.Size(m)
}
func (m *UpdateAccountRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateAccountRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateAccountRequest proto.InternalMessageInfo

func (m *UpdateAccountRequest) GetAccount() *Credential {
	if m != nil {
		return m.Account
	}
	return nil
}

type UpdateAccountResponse struct {
	Code                 int32       `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Detail               string      `protobuf:"bytes,2,opt,name=detail,proto3" json:"detail,omitempty"`
	Account              *Credential `protobuf:"bytes,3,opt,name=account,proto3" json:"account,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *UpdateAccountResponse) Reset()         { *m = UpdateAccountResponse{} }
func (m *UpdateAccountResponse) String() string { return proto.CompactTextString(m) }
func (*UpdateAccountResponse) ProtoMessage()    {}
func (*UpdateAccountResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_5d492a0187472a3b, []int{6}
}

func (m *UpdateAccountResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateAccountResponse.Unmarshal(m, b)
}
func (m *UpdateAccountResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateAccountResponse.Marshal(b, m, deterministic)
}
func (m *UpdateAccountResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateAccountResponse.Merge(m, src)
}
func (m *UpdateAccountResponse) XXX_Size() int {
	return xxx_messageInfo_UpdateAccountResponse.Size(m)
}
func (m *UpdateAccountResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateAccountResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateAccountResponse proto.InternalMessageInfo

func (m *UpdateAccountResponse) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *UpdateAccountResponse) GetDetail() string {
	if m != nil {
		return m.Detail
	}
	return ""
}

func (m *UpdateAccountResponse) GetAccount() *Credential {
	if m != nil {
		return m.Account
	}
	return nil
}

type DeleteAccountRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteAccountRequest) Reset()         { *m = DeleteAccountRequest{} }
func (m *DeleteAccountRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteAccountRequest) ProtoMessage()    {}
func (*DeleteAccountRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_5d492a0187472a3b, []int{7}
}

func (m *DeleteAccountRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteAccountRequest.Unmarshal(m, b)
}
func (m *DeleteAccountRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteAccountRequest.Marshal(b, m, deterministic)
}
func (m *DeleteAccountRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteAccountRequest.Merge(m, src)
}
func (m *DeleteAccountRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteAccountRequest.Size(m)
}
func (m *DeleteAccountRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteAccountRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteAccountRequest proto.InternalMessageInfo

func (m *DeleteAccountRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type DeleteAccountResponse struct {
	Code                 int32    `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Detail               string   `protobuf:"bytes,2,opt,name=detail,proto3" json:"detail,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteAccountResponse) Reset()         { *m = DeleteAccountResponse{} }
func (m *DeleteAccountResponse) String() string { return proto.CompactTextString(m) }
func (*DeleteAccountResponse) ProtoMessage()    {}
func (*DeleteAccountResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_5d492a0187472a3b, []int{8}
}

func (m *DeleteAccountResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteAccountResponse.Unmarshal(m, b)
}
func (m *DeleteAccountResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteAccountResponse.Marshal(b, m, deterministic)
}
func (m *DeleteAccountResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteAccountResponse.Merge(m, src)
}
func (m *DeleteAccountResponse) XXX_Size() int {
	return xxx_messageInfo_DeleteAccountResponse.Size(m)
}
func (m *DeleteAccountResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteAccountResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteAccountResponse proto.InternalMessageInfo

func (m *DeleteAccountResponse) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *DeleteAccountResponse) GetDetail() string {
	if m != nil {
		return m.Detail
	}
	return ""
}

type LoginRequest struct {
	Username             string   `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Email                string   `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	Password             string   `protobuf:"bytes,3,opt,name=password,proto3" json:"password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoginRequest) Reset()         { *m = LoginRequest{} }
func (m *LoginRequest) String() string { return proto.CompactTextString(m) }
func (*LoginRequest) ProtoMessage()    {}
func (*LoginRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_5d492a0187472a3b, []int{9}
}

func (m *LoginRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginRequest.Unmarshal(m, b)
}
func (m *LoginRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginRequest.Marshal(b, m, deterministic)
}
func (m *LoginRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginRequest.Merge(m, src)
}
func (m *LoginRequest) XXX_Size() int {
	return xxx_messageInfo_LoginRequest.Size(m)
}
func (m *LoginRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginRequest.DiscardUnknown(m)
}

var xxx_messageInfo_LoginRequest proto.InternalMessageInfo

func (m *LoginRequest) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *LoginRequest) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *LoginRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type LoginResponse struct {
	Code                 int32       `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Detail               string      `protobuf:"bytes,2,opt,name=detail,proto3" json:"detail,omitempty"`
	Token                *auth.Token `protobuf:"bytes,3,opt,name=token,proto3" json:"token,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *LoginResponse) Reset()         { *m = LoginResponse{} }
func (m *LoginResponse) String() string { return proto.CompactTextString(m) }
func (*LoginResponse) ProtoMessage()    {}
func (*LoginResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_5d492a0187472a3b, []int{10}
}

func (m *LoginResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginResponse.Unmarshal(m, b)
}
func (m *LoginResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginResponse.Marshal(b, m, deterministic)
}
func (m *LoginResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginResponse.Merge(m, src)
}
func (m *LoginResponse) XXX_Size() int {
	return xxx_messageInfo_LoginResponse.Size(m)
}
func (m *LoginResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginResponse.DiscardUnknown(m)
}

var xxx_messageInfo_LoginResponse proto.InternalMessageInfo

func (m *LoginResponse) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *LoginResponse) GetDetail() string {
	if m != nil {
		return m.Detail
	}
	return ""
}

func (m *LoginResponse) GetToken() *auth.Token {
	if m != nil {
		return m.Token
	}
	return nil
}

type LogoutRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LogoutRequest) Reset()         { *m = LogoutRequest{} }
func (m *LogoutRequest) String() string { return proto.CompactTextString(m) }
func (*LogoutRequest) ProtoMessage()    {}
func (*LogoutRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_5d492a0187472a3b, []int{11}
}

func (m *LogoutRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LogoutRequest.Unmarshal(m, b)
}
func (m *LogoutRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LogoutRequest.Marshal(b, m, deterministic)
}
func (m *LogoutRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LogoutRequest.Merge(m, src)
}
func (m *LogoutRequest) XXX_Size() int {
	return xxx_messageInfo_LogoutRequest.Size(m)
}
func (m *LogoutRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_LogoutRequest.DiscardUnknown(m)
}

var xxx_messageInfo_LogoutRequest proto.InternalMessageInfo

type LogoutResponse struct {
	Code                 int32    `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Detail               string   `protobuf:"bytes,2,opt,name=detail,proto3" json:"detail,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LogoutResponse) Reset()         { *m = LogoutResponse{} }
func (m *LogoutResponse) String() string { return proto.CompactTextString(m) }
func (*LogoutResponse) ProtoMessage()    {}
func (*LogoutResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_5d492a0187472a3b, []int{12}
}

func (m *LogoutResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LogoutResponse.Unmarshal(m, b)
}
func (m *LogoutResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LogoutResponse.Marshal(b, m, deterministic)
}
func (m *LogoutResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LogoutResponse.Merge(m, src)
}
func (m *LogoutResponse) XXX_Size() int {
	return xxx_messageInfo_LogoutResponse.Size(m)
}
func (m *LogoutResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_LogoutResponse.DiscardUnknown(m)
}

var xxx_messageInfo_LogoutResponse proto.InternalMessageInfo

func (m *LogoutResponse) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *LogoutResponse) GetDetail() string {
	if m != nil {
		return m.Detail
	}
	return ""
}

func init() {
	proto.RegisterType((*Credential)(nil), "go.micro.bookstore.srv.account.Credential")
	proto.RegisterType((*CreateAccountRequest)(nil), "go.micro.bookstore.srv.account.CreateAccountRequest")
	proto.RegisterType((*CreateAccountResponse)(nil), "go.micro.bookstore.srv.account.CreateAccountResponse")
	proto.RegisterType((*GetAccountRequest)(nil), "go.micro.bookstore.srv.account.GetAccountRequest")
	proto.RegisterType((*GetAccountResponse)(nil), "go.micro.bookstore.srv.account.GetAccountResponse")
	proto.RegisterType((*UpdateAccountRequest)(nil), "go.micro.bookstore.srv.account.UpdateAccountRequest")
	proto.RegisterType((*UpdateAccountResponse)(nil), "go.micro.bookstore.srv.account.UpdateAccountResponse")
	proto.RegisterType((*DeleteAccountRequest)(nil), "go.micro.bookstore.srv.account.DeleteAccountRequest")
	proto.RegisterType((*DeleteAccountResponse)(nil), "go.micro.bookstore.srv.account.DeleteAccountResponse")
	proto.RegisterType((*LoginRequest)(nil), "go.micro.bookstore.srv.account.LoginRequest")
	proto.RegisterType((*LoginResponse)(nil), "go.micro.bookstore.srv.account.LoginResponse")
	proto.RegisterType((*LogoutRequest)(nil), "go.micro.bookstore.srv.account.LogoutRequest")
	proto.RegisterType((*LogoutResponse)(nil), "go.micro.bookstore.srv.account.LogoutResponse")
}

func init() { proto.RegisterFile("proto/account/account.proto", fileDescriptor_5d492a0187472a3b) }

var fileDescriptor_5d492a0187472a3b = []byte{
	// 620 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xc4, 0x56, 0x5f, 0x6b, 0xdb, 0x30,
	0x10, 0xaf, 0x93, 0x3a, 0x6d, 0xae, 0x6b, 0xc7, 0x44, 0x3a, 0x8c, 0xcb, 0xb6, 0xe2, 0xc1, 0x28,
	0x63, 0xb5, 0x59, 0xb7, 0xc1, 0x1e, 0xf6, 0x52, 0x52, 0x28, 0x85, 0x3d, 0x99, 0x6d, 0x4f, 0x81,
	0xe0, 0x58, 0x4a, 0x22, 0xea, 0x58, 0x99, 0x24, 0x67, 0x6f, 0x7d, 0x1c, 0xec, 0x7b, 0xec, 0x1b,
	0xed, 0x0b, 0x0d, 0x49, 0x76, 0xfe, 0x38, 0xc9, 0x9c, 0x14, 0x46, 0x5f, 0xda, 0xe8, 0xee, 0x7e,
	0xf7, 0x3b, 0xdd, 0xe9, 0x77, 0x09, 0x9c, 0x8c, 0x39, 0x93, 0x2c, 0x88, 0xe2, 0x98, 0x65, 0xa9,
	0x2c, 0xfe, 0xfb, 0xda, 0x8a, 0x9e, 0x0f, 0x98, 0x3f, 0xa2, 0x31, 0x67, 0x7e, 0x8f, 0xb1, 0x5b,
	0x21, 0x19, 0x27, 0xbe, 0xe0, 0x13, 0x3f, 0x8f, 0x72, 0xaf, 0x07, 0x54, 0x0e, 0xb3, 0x9e, 0x1f,
	0xb3, 0x51, 0x10, 0x0d, 0x47, 0x11, 0x4e, 0x33, 0x9e, 0x89, 0x60, 0xc0, 0xce, 0x35, 0xea, 0x7c,
	0x8a, 0x0a, 0xa2, 0x4c, 0x0e, 0x03, 0xc1, 0x27, 0x41, 0x4e, 0xa7, 0x8e, 0xea, 0x8f, 0x21, 0xf2,
	0x7e, 0xd7, 0x00, 0xda, 0x9c, 0x60, 0x92, 0x4a, 0x1a, 0x25, 0xe8, 0x08, 0x6a, 0x14, 0x3b, 0xd6,
	0xa9, 0x75, 0xd6, 0x0c, 0x6b, 0x14, 0x23, 0x17, 0xf6, 0x33, 0x41, 0x78, 0x1a, 0x8d, 0x88, 0x53,
	0xd3, 0xd6, 0xe9, 0x19, 0xb5, 0xc0, 0x26, 0xa3, 0x88, 0x26, 0x4e, 0x5d, 0x3b, 0xcc, 0x41, 0x21,
	0xc6, 0x91, 0x10, 0x3f, 0x18, 0xc7, 0xce, 0xae, 0x41, 0x14, 0x67, 0xf4, 0x0c, 0x60, 0xcc, 0x59,
	0x9f, 0x26, 0xa4, 0x4b, 0xb1, 0x63, 0x6b, 0x6f, 0x33, 0xb7, 0xdc, 0x60, 0x74, 0x02, 0x4d, 0x55,
	0x19, 0xe3, 0xca, 0xdb, 0x30, 0x58, 0x63, 0xb8, 0xc1, 0xe8, 0x05, 0x1c, 0x50, 0xd1, 0x9d, 0x10,
	0x4e, 0xfb, 0x94, 0x60, 0x67, 0xef, 0xd4, 0x3a, 0xdb, 0x0f, 0x81, 0x8a, 0x6f, 0xb9, 0x45, 0x25,
	0x4f, 0x22, 0x21, 0xbb, 0x09, 0x1b, 0xd0, 0xd4, 0xd9, 0x3f, 0xb5, 0xce, 0xea, 0x61, 0x53, 0x59,
	0x3e, 0x2b, 0x83, 0x72, 0xc7, 0x9c, 0x44, 0x92, 0xe0, 0x6e, 0x24, 0x9d, 0xa6, 0x71, 0xe7, 0x96,
	0x4b, 0xa9, 0xdc, 0xd9, 0x18, 0x17, 0x6e, 0x30, 0xee, 0xdc, 0x72, 0x29, 0xbd, 0x0e, 0xb4, 0xda,
	0x3a, 0xf6, 0xd2, 0x0c, 0x20, 0x24, 0xdf, 0x33, 0x22, 0x24, 0xba, 0x82, 0xbd, 0x7c, 0x24, 0xba,
	0x69, 0x07, 0x17, 0xaf, 0xfd, 0x7f, 0x4f, 0xce, 0x9f, 0x35, 0x3b, 0x2c, 0xa0, 0xde, 0x2f, 0x0b,
	0x8e, 0x4b, 0xe9, 0xc5, 0x98, 0xa5, 0x82, 0x20, 0x04, 0xbb, 0x31, 0xc3, 0x44, 0x27, 0xb7, 0x43,
	0xfd, 0x19, 0x3d, 0x85, 0x06, 0x26, 0x52, 0x35, 0xde, 0x4c, 0x24, 0x3f, 0xcd, 0xd7, 0x52, 0xbf,
	0x7f, 0x2d, 0x2f, 0xe1, 0xc9, 0x35, 0x91, 0xa5, 0x6b, 0x96, 0x9e, 0x85, 0xf7, 0xd3, 0x02, 0x34,
	0x1f, 0xf5, 0x60, 0xd5, 0x76, 0xa0, 0xf5, 0x55, 0x0f, 0xe9, 0xbf, 0xcd, 0xa5, 0x94, 0xfe, 0xc1,
	0x6e, 0xfa, 0x0a, 0x5a, 0x57, 0x24, 0x21, 0x4b, 0x37, 0x2d, 0x8f, 0xa6, 0x0d, 0xc7, 0xa5, 0xb8,
	0xed, 0x4b, 0xf6, 0x3a, 0xf0, 0x48, 0xab, 0xa6, 0x20, 0x99, 0x5f, 0x03, 0xd6, 0xba, 0x35, 0x50,
	0x5b, 0xb7, 0x06, 0xea, 0x8b, 0x6b, 0xc0, 0xcb, 0xe0, 0x30, 0xcf, 0x7e, 0x8f, 0x6e, 0x7e, 0x04,
	0x5b, 0xb2, 0x5b, 0x92, 0xe6, 0xbd, 0xf4, 0xd6, 0xf6, 0x52, 0xed, 0xb8, 0x2f, 0x2a, 0x32, 0x34,
	0x00, 0xef, 0xb1, 0xa6, 0x65, 0x59, 0xd1, 0x3a, 0xef, 0x13, 0x1c, 0x15, 0x86, 0xed, 0x0b, 0xb9,
	0xf8, 0x63, 0xc3, 0x5e, 0xde, 0x63, 0x74, 0x07, 0x87, 0x0b, 0xfa, 0x45, 0xef, 0x37, 0x18, 0xf1,
	0xd2, 0xab, 0x75, 0x3f, 0x6c, 0x89, 0x32, 0x55, 0x7b, 0x3b, 0x28, 0x03, 0x98, 0xc9, 0x11, 0xbd,
	0xad, 0x4a, 0xb3, 0x24, 0x70, 0xf7, 0x62, 0x1b, 0xc8, 0x94, 0xf6, 0x0e, 0x0e, 0x17, 0xe4, 0x51,
	0x7d, 0xed, 0x55, 0x62, 0xad, 0xbe, 0xf6, 0x4a, 0x0d, 0x1a, 0xfe, 0x85, 0xb7, 0x5e, 0xcd, 0xbf,
	0x4a, 0x42, 0xd5, 0xfc, 0x2b, 0x05, 0xe5, 0xed, 0xa0, 0x3e, 0xd8, 0xe6, 0xcb, 0xe5, 0x4d, 0x55,
	0x86, 0x79, 0x35, 0xb9, 0xe7, 0x1b, 0x46, 0x4f, 0x79, 0x28, 0x34, 0xcc, 0x43, 0x45, 0x9b, 0x40,
	0x67, 0x2f, 0xdc, 0xf5, 0x37, 0x0d, 0x2f, 0xa8, 0x7a, 0x0d, 0xfd, 0xb3, 0xe0, 0xdd, 0xdf, 0x00,
	0x00, 0x00, 0xff, 0xff, 0x0a, 0x81, 0x3c, 0x96, 0x9e, 0x08, 0x00, 0x00,
}
